#!/usr/bin/env python3
"""Build the local, self-contained audit index; never publish it with the site."""
import json
from pathlib import Path
from html import escape
ROOT=Path(__file__).resolve().parent.parent
OUT=ROOT/'outputs/publication-2026-09-30'
d=json.loads((OUT/'audit-summary.json').read_text())
names={'home':'Accueil','horses':'Chevaux','programmes':'Formation','facilities':'Installations','for-sale':'Ventes','references':'Références','houses':'Maisons','ortho-24':'La Grange','ortho-25':'Le Cottage','activities':'Alentours','legal':'Mentions légales','privacy':'Confidentialité','team':'Équipe','boarding':'Pension & soins','contact':'Contact & accès'}
rows=''
for name,label in names.items():
 mobile=next(r for r in d['medians'] if r['name']==name and r['profile']=='mobile');desktop=next(r for r in d['medians'] if r['name']==name and r['profile']=='desktop')
 rows+=f'<tr><th>{escape(label)}</th><td>{mobile["scores"]["performance"]}</td><td>{desktop["scores"]["performance"]}</td><td>{mobile["metrics"]["lcpMs"]/1000:.2f} s</td><td>{mobile["metrics"]["cls"]:.3f}</td></tr>'
captures=''
for slug,label in [('home','Accueil'),('team','Équipe'),('horses-boarding','Pension & soins'),('contact','Contact & accès'),('houses-ortho-25','Le Cottage')]:
 for width in [390,1440]:
  f=f'captures-fr/viewport-{slug}-{width}.png';full=f'captures-fr/current-{slug}-{width}.png'
  captures+=f'<figure><a href="{full}"><img loading="lazy" src="{f}" alt="{label}, largeur {width} pixels"></a><figcaption>{label} · {width} px · <a href="{full}">Capture complète</a></figcaption></figure>'
html='''<!doctype html><html lang="fr"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Prépinson · Dossier de livraison</title><style>
*{box-sizing:border-box}body{margin:0;background:#f5f4ee;color:#223c30;font:16px/1.6 system-ui,sans-serif}header{background:#223c30;color:white;padding:64px max(7vw,24px)}main{max-width:1160px;margin:auto;padding:48px 24px}h1{font:normal clamp(38px,5vw,68px)/1.1 Georgia,serif;max-width:850px}h2{font:normal 34px/1.2 Georgia,serif;margin-top:56px}h3{font-size:19px}a{color:inherit;text-underline-offset:4px}header p{max-width:800px}.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:20px}.card{padding:24px;border:1px solid #cdd5ca}.card strong{display:block;font:normal 40px Georgia,serif}.notice{border-left:3px solid #a28b60;padding:16px 24px;background:#ecebdf}table{border-collapse:collapse;width:100%;font-variant-numeric:tabular-nums}td,th{text-align:left;padding:12px 8px;border-bottom:1px solid #cdd5ca}thead{background:#e7eadf}.table-wrap{overflow-x:auto}.gallery{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:24px}figure{margin:0}figure img{width:100%;height:330px;object-fit:contain;background:#e7eadf;border:1px solid #d5dacd}figcaption{font-size:14px;margin-top:10px}small{display:block;color:#586456}.links{display:flex;flex-wrap:wrap;gap:14px}footer{padding:40px 24px;text-align:center;border-top:1px solid #cdd5ca}@media print{header{background:white;color:#223c30;padding:20px}main{padding:20px}.gallery{display:none}h2{break-after:avoid}tr{break-inside:avoid}}
</style><header><p>UNMISSABL · HARAS DE PRÉPINSON · 30 SEPTEMBRE 2026</p><h1>Une version complète.<br>Des vérifications documentées.</h1><p>Navigation, contenus et médias finalisés dans six langues. Version disponible en prévisualisation ; bascule du domaine encore à effectuer après les contrôles opérationnels.</p><p><a href="https://deploy-preview-1--prepinson.netlify.app/fr/">Voir la version déployée ↗</a></p></header><main>
<div class="cards"><div class="card"><strong>90</strong>pages publiques · 6 langues</div><div class="card"><strong>98–100</strong>performance mobile, laboratoire</div><div class="card"><strong>100</strong>performance ordinateur</div><div class="card"><strong>1 440</strong>configurations Chrome et WebKit</div></div>
<h2>Ce qui est livré</h2><p>Le haras reste prioritaire. Les menus et le footer suivent la même hiérarchie. Contact est un lien direct. Les pages Équipe, Pension & soins et Contact & accès complètent les parcours existants. Les chevaux, pedigrees et photos ont été corrigés. La Grange et Le Cottage conservent leurs URL et plateformes de réservation.</p><p>Le seul cookie du site retient la langue pendant la session, après un choix explicite. Les cartes et plateformes externes restent des liens. Aucun bandeau ni outil de suivi individuel n’est ajouté.</p>
<h2>Les points à terminer avant la bascule</h2><div class="notice"><ul><li>Configurer les destinataires des notifications Netlify puis vérifier la réception en boîte mail.</li><li>Terminer la recette dans Firefox et Safari installé : contraintes de l’environnement local. WebKit automatisé passe.</li><li>Confirmer les droits des médias, sauvegarder WordPress, rattacher le domaine et préserver la messagerie.</li><li>Accéder aux comptes propriétaires Search Console et Bing, puis soumettre le sitemap après publication.</li></ul></div>
<h2>Résultats datés</h2><p>Médiane de trois mesures Lighthouse par type de page et profil. Quinze pages en anglais représentent les quinze modèles. Les tests de contenu, de mise en page et d’accessibilité couvrent les six langues. Le Cottage a été remesuré après sa dernière optimisation.</p><p><strong>Accessibilité, bonnes pratiques et SEO technique : 100</strong> sur les trente combinaisons page/profil. Aucune violation axe détectée sur les 90 pages. LCP mobile maximal : 2,40 s. CLS mesuré : 0.</p><div class="table-wrap"><table><thead><tr><th>Page</th><th>Mobile</th><th>Ordinateur</th><th>LCP mobile</th><th>CLS mobile</th></tr></thead><tbody>'''+rows+'''</tbody></table></div><small>Ces chiffres sont des mesures de laboratoire, pas des Core Web Vitals réels. L’INP doit être observé avec des visites réelles. Un score SEO technique ne garantit aucun classement Google ni citation par une IA. La preview reste volontairement non indexable.</small>
<h2>Contrôles sur la version déployée</h2><p>118 contrôles HTTP réussis : pages, redirections, médias, sitemap, en-têtes, cache et Instagram. 108 contrôles de navigation et sept cas de choix de langue réussis. Le flux Instagram retourne six publications et un état sain. Les 25 liens externes vérifiés répondent.</p><p>Une demande et une inscription fictive ont été enregistrées et retrouvées dans Netlify. La confirmation d’inscription est correcte. Les deux enregistrements techniques ont été écartés des listes actives. La réception par email attend la configuration des notifications.</p><div class="links"><a href="audit-summary.json">Synthèse JSON</a><a href="lighthouse-final/summary.md">Audits initiaux complets</a><a href="lighthouse-cottage-final/summary.md">Mesure finale du Cottage</a><a href="deployment.json">Contrôles Netlify</a><a href="netlify-forms.json">Test des formulaires</a></div>
<p>Mesures complémentaires sur Netlify : performance mobile 100 pour l’accueil et Le Cottage (médiane de trois essais), accessibilité et bonnes pratiques 100. SEO 69 : la preview bloque volontairement l’indexation.</p><p><a href="lighthouse-netlify/summary.md">Mesures sur la preview Netlify</a></p><h2>Captures françaises</h2><p>Les liens ouvrent les captures complètes. Les contrôles responsive couvrent aussi la largeur intermédiaire de 761 px.</p><div class="gallery">'''+captures+'''</div><h2>Maintenance et retour arrière</h2><p>Le dossier de publication accompagne les résultats : conservation des données, contrôle des formulaires, sauvegarde, retour arrière, messagerie et suivi SEO.</p><p><a href="../../docs/PUBLICATION.md">Consignes de publication et de maintenance</a> · <a href="https://github.com/matthieuDa/prepinson/pull/1">Version préparée sur GitHub</a></p></main><footer>Prépinson · Dossier de livraison UNMISSABL · 30 septembre 2026</footer></html>'''
(OUT/'livraison.html').write_text(html)
print(OUT/'livraison.html')
