from pathlib import Path
import json
OUT=Path('dist')
IG='https://www.instagram.com/haras_de_prepinson/'
IG_HOUSE='https://www.instagram.com/prepinson_the_house/'
CASA='https://www.casapilot.com/en/1091854-holiday-home-in-la-roche-en-ardenne-ardennes-and-eifel-belgium'
AIR='https://www.airbnb.com/h/ortho25'
ARROW='<span aria-hidden="true">↗</span>'
brand='<a class="brand" href="/" aria-label="Prépinson home"><img src="/assets/logo.png" alt=""><span class="wordmark">PRÉPINSON<small>HARAS DE PRÉPINSON</small></span></a>'
def header(active=''):
 links=[('/#haras','The haras'),('/#expertise','Our expertise'),('/horses/','Horses'),('/#journal','Journal'),('/houses/','Houses')]
 nav=''.join(f'<a href="{u}"'+(' aria-current="page"' if t==active else '')+f'>{t}</a>' for u,t in links)
 return f'<a class="skip-link" href="#main">Skip to content</a><header class="nav">{brand}<nav class="navlinks" aria-label="Main navigation">{nav}<a class="nav-book" href="mailto:haras@prepinson.com">Get in touch <span>↗</span></a></nav><button class="menu-toggle" aria-expanded="false" aria-controls="mobile-menu">Menu ☰</button></header><nav id="mobile-menu" class="mobile-nav" aria-label="Mobile navigation">{nav}<small>ORTHO · BELGIAN ARDENNES</small></nav>'
def footer():
 return f'''<section id="contact" class="contact-section"><div class="container contact-layout"><div class="contact-copy"><p class="eyebrow">A SHARED PASSION STARTS A CONVERSATION.</p><h2>Let’s talk<br><em>horses.</em></h2><p>Tell us about your horse, your plans or the stay you have in mind. We will come back to you personally.</p><div class="contact-direct"><a href="mailto:haras@prepinson.com">haras@prepinson.com ↗</a><a href="mailto:thehouse@prepinson.com">thehouse@prepinson.com ↗</a><a href="tel:+32470851310">+32 470 85 13 10</a></div></div><form class="contact-form" name="contact" method="POST" data-netlify="true" netlify-honeypot="company"><input type="hidden" name="form-name" value="contact"><p class="form-trap"><label>Leave this field empty <input name="company"></label></p><div class="form-grid"><label><span>Your name</span><input type="text" name="name" autocomplete="name" required></label><label><span>Your email</span><input type="email" name="email" autocomplete="email" required></label></div><label><span>I am interested in</span><select name="interest"><option>Horse boarding</option><option>Young horse training</option><option>Breeding</option><option>Horses for sale</option><option>A stay at Prépinson</option><option>Something else</option></select></label><label><span>Your message</span><textarea name="message" rows="5" required></textarea></label><button class="btn dark" type="submit">Send message {ARROW}</button></form></div></section><footer class="footer haras-footer"><div class="container"><div class="newsletter-row"><div><p class="eyebrow">FROM PRÉPINSON, OCCASIONALLY.</p><h3>News from the haras.</h3></div><form class="newsletter-form" name="newsletter" method="POST" data-netlify="true"><input type="hidden" name="form-name" value="newsletter"><label><span class="visually-hidden">Email address</span><input type="email" name="email" autocomplete="email" placeholder="Email address" required></label><button type="submit" aria-label="Subscribe to the mailing list">Subscribe {ARROW}</button></form></div><div class="footer-social"><div><p class="eyebrow">HORSES</p><a href="mailto:haras@prepinson.com">haras@prepinson.com</a><a href="{IG}" target="_blank" rel="noopener">@haras_de_prepinson ↗</a></div><div><p class="eyebrow">HOUSES</p><a href="mailto:thehouse@prepinson.com">thehouse@prepinson.com</a><a href="{IG_HOUSE}" target="_blank" rel="noopener">@prepinson_the_house ↗</a></div><div><p class="eyebrow">VISIT</p><p>Ortho 24<br>6983 La Roche-en-Ardenne<br>Belgium</p></div></div><div class="footer-signature">PRÉPINSON</div><div class="footer-bottom"><span>© 2026 HARAS DE PRÉPINSON</span><a href="https://maps.google.com/?q=Prepinson+Ortho+Belgium" target="_blank" rel="noopener">FIND THE HARAS ↗</a></div></div></footer>'''

def team():
 return '''<section id="team" class="team-section"><div class="container"><div class="team-heading"><p class="eyebrow">THE PEOPLE OF PRÉPINSON</p><h2>Experience, instinct<br><em>and daily care.</em></h2><p>Prépinson is shaped by a small, committed team and a shared belief: every horse deserves individual attention, patience and the right environment.</p></div><figure class="team-group-photo"><img src="/assets/prepinson-haras-team.webp" alt="The Haras de Prépinson team together outdoors" loading="lazy"><figcaption>Together, every day, for the horses.</figcaption></figure><div class="team-grid"><article class="team-card"><img src="/assets/eva-schiller.jpg" alt="Eva Schiller, Manager and Founder of Prépinson" loading="lazy"><div><p class="eyebrow">MANAGER & FOUNDER</p><h3>Eva Schiller</h3><a href="mailto:eva.schiller@prepinson.com">eva.schiller@prepinson.com ↗</a><a href="tel:+352691223836">+352 691 22 38 36</a></div></article><article class="team-card"><img src="/assets/nicolas-derouault.jpg" alt="Nicolas Derouault, Site Manager of Prépinson" loading="lazy"><div><p class="eyebrow">SITE MANAGER</p><h3>Nicolas Derouault</h3><a href="mailto:nicolas.derouault@prepinson.com">nicolas.derouault@prepinson.com ↗</a><a href="tel:+32470851310">+32 470 85 13 10</a></div></article></div></div></section>'''
def dialogs():
 return '''<dialog id="film-dialog" class="dialog" aria-label="A film of Prépinson"><button class="dialog-close" data-close aria-label="Close film">×</button><video controls playsinline preload="none"></video><p class="dialog-caption">Prépinson · Film by Papilio Productions</p></dialog><dialog id="lightbox" class="dialog" aria-label="Photo gallery"><button class="dialog-close" data-close aria-label="Close gallery">×</button><img alt=""><div class="lightbox-controls"><button data-prev aria-label="Previous photograph">←</button><span class="lightbox-label"></span><button data-next aria-label="Next photograph">→</button></div></dialog>'''
def page(path,title,description,content,active=''):
 route='/' if not path else '/'+path.strip('/')+'/'
 schema={'@context':'https://schema.org','@type':'LocalBusiness','name':'Prépinson','url':'https://www.prepinson.com','description':'Haras de Prépinson in Ortho, Belgian Ardennes. Horse breeding, young horse training, show jumping and horse boarding in Belgium.','email':'haras@prepinson.com','telephone':'+32470851310','address':{'@type':'PostalAddress','streetAddress':'Ortho 24','postalCode':'6983','addressLocality':'La Roche-en-Ardenne','addressCountry':'BE'},'sameAs':[IG,IG_HOUSE]}
 s=f'''<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{title}</title><meta name="description" content="{description}"><meta name="theme-color" content="#23372c"><link rel="canonical" href="https://www.prepinson.com{route}"><meta property="og:title" content="{title}"><meta property="og:description" content="{description}"><meta property="og:type" content="website"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/styles.css"><script type="application/ld+json">{json.dumps(schema)}</script><script src="/app.js" defer></script></head><body>{header(active)}<main id="main">{content}</main>{footer()}{dialogs()}</body></html>'''
 p=OUT/path/'index.html';p.parent.mkdir(parents=True,exist_ok=True);p.write_text(s)
def image(name,alt,extra=''):
 return f'<img src="/assets/{name}" alt="{alt}" loading="lazy" {extra}>'
def hero(eyebrow,title,subtitle='',photo='hero.jpg',buttons='',video=False,inner=False):
 media=f'<video class="hero-media" autoplay muted loop playsinline poster="/assets/{photo}" aria-hidden="true"><source src="/assets/estate-film.mp4" type="video/mp4"></video>' if video else f'<img class="hero-media" src="/assets/{photo}" alt="Prépinson in the Belgian Ardennes" fetchpriority="high">'
 return f'''<section class="hero {'inner-hero' if inner else ''}">{media}<div class="hero-shade"></div><div class="hero-content reveal"><p class="eyebrow">{eyebrow}</p><h1>{title}</h1>{f'<p>{subtitle}</p>' if subtitle else ''}{buttons}</div><div class="hero-bottom"><span class="location"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.4" aria-hidden="true"><path d="M19 10c0 5-7 11-7 11S5 15 5 10a7 7 0 1 1 14 0Z"/><circle cx="12" cy="10" r="2"/></svg>Ortho, Belgian Ardennes</span><a class="scroll-link" href="#discover">A little closer to nature <span>↓</span></a><div style="display:flex;gap:15px;align-items:center"><button class="film-button" data-film="/assets/estate-film.mp4"><span class="circle" aria-hidden="true">▷</span>Watch the film</button>{'<button data-pause aria-label="Pause background film" class="circle">Ⅱ</button>' if video else ''}</div></div></section>'''
def moments():
 imgs=[('horse-1.jpg','Life with horses at Prépinson'),('house-3.jpg','The riverside town of La Roche-en-Ardenne'),('estate-2.jpg','The estate from above'),('horse-4.jpg','Daily care for horses at Prépinson')]
 return f'''<section class="moments container"><div class="section-head"><div><p class="eyebrow">The everyday, a little extraordinary</p><h2>Life at Prépinson.</h2></div><a class="text-link" href="{IG}" target="_blank" rel="noopener">Follow along on Instagram {ARROW}</a></div><div class="moments-grid">{''.join(f'<a class="moment" href="{IG}" target="_blank" rel="noopener">'+image(n,a)+'</a>' for n,a in imgs)}</div></section>'''
home=Path('work/home-haras.html').read_text().replace('<section id="journal"',team()+Path('src/journal.html').read_text()+'<section id="journal"')
page('', 'Haras de Prépinson — A Life Dedicated to Horses','Haras de Prépinson, Belgium. Professional young horse training, breeding, show jumping and exceptional horse boarding in the Belgian Ardennes.',home)

def gallery(items):
 return '<div class="gallery">'+''.join(f'<button data-gallery aria-label="Enlarge photograph: {a}">'+image(n,a)+'</button>' for n,a in items)+'</div>'
horses=hero('Haras de Prépinson · Belgium','Great horses.<br><em>Thoughtful beginnings.</em>','Professional care. Patient training. Room to reach their potential.',photo='prepinson-outdoor-jumping-arena.webp',inner=True,buttons=f'<a class="btn light" href="{IG}" target="_blank" rel="noopener">Horses for sale on Instagram {ARROW}</a>')
horses+='''<section id="discover" class="intro container"><div><p class="eyebrow">Our equestrian world</p><h2>Every horse.<br><em>Every possibility.</em></h2></div><p class="body-copy">At our haras in Belgium, good horsemanship begins with understanding the individual. From foals and young horses to sport horses, our approach combines professional training with daily, attentive care.</p></section><section class="services container"><div class="services-grid"><article id="boarding" class="service"><p class="eyebrow">01 / Care & boarding</p><h3>A place to thrive.</h3><p>Horse pension in a peaceful setting, with daily supervision and space for every stage of life.</p><ul><li>Boarding for young and retired horses</li><li>Broodmare care and foaling supervision</li><li>Shared boxes and time in the fields</li><li>Coordination of hoof care and routine health needs</li></ul><a class="text-link" href="mailto:haras@prepinson.com?subject=Horse%20boarding%20enquiry">Enquire about boarding ↗</a></article><article id="training" class="service"><p class="eyebrow">02 / Training & development</p><h3>Potential, patiently developed.</h3><p>Professional young horse training, from breaking in to confident work in the arena.</p><ul><li>Individual training in show jumping and dressage</li><li>Full-time training and competition preparation</li><li>Professional equestrian facilities</li><li>Lessons with your own horse</li></ul><a class="text-link" href="mailto:haras@prepinson.com?subject=Horse%20training%20enquiry">Talk to us about your horse ↗</a></article></div>'''
horses+=f'<div class="wide-image">{image("prepinson-daily-horse-care.webp","A calm moment of daily horse care at Prépinson")}<a class="film-button" href="https://www.youtube.com/watch?v=9ogNVCE1DrM" target="_blank" rel="noopener"><span class="circle">▷</span>Explore our facilities</a></div></section>'
horses+='''<section id="breeding" class="references"><div class="container"><div class="section-head"><div><p class="eyebrow">Bred at Prépinson</p><h2>A few of our stories.</h2></div><p class="small-note">Selected horses from our breeding programme.</p></div><div class="reference-grid"><article class="reference-card"><p class="eyebrow">Born 2019 · Haras de Prépinson</p><h3>Juni de Prépinson</h3><p class="pedigree">Silver Deux de Virton H D C<br>× Firsty de Prépinson</p></article><article class="reference-card"><p class="eyebrow">Born 2018 · Haras de Prépinson</p><h3>Dalton de Prépinson</h3><p class="pedigree">Don Juan de Hus<br>× Samsara de Hus</p></article><article class="reference-card"><p class="eyebrow">Born 2017 · Haras de Prépinson</p><h3>Dakota de Prépinson</h3><p class="pedigree">Don Juan de Hus<br>× Samsara de Hus</p></article></div></div></section>'''
horses+=f'<section class="instagram-band"><div><p class="eyebrow">Find your next partner</p><h2>Our latest horses. On Instagram.</h2><p>For horses currently for sale, new arrivals and everyday life at the haras.</p></div><a class="btn light" href="{IG}" target="_blank" rel="noopener">@haras_de_prepinson {ARROW}</a></section>'
horses+='<section class="moments archive-gallery container"><div class="section-head"><div><p class="eyebrow">Around the haras</p><h2>In good company.</h2></div><p class="small-note">A wider look at life, care and training at Prépinson.</p></div>'+gallery([('prepinson-outdoor-arena.webp','The outdoor riding arena at Haras de Prépinson'),('prepinson-stables-flowers.webp','Flowers welcoming visitors to the Prépinson stables'),('prepinson-rider-saddle-detail.webp','A rider preparing in the saddle at Prépinson'),('prepinson-bay-horse-outdoors.webp','A bay horse enjoying the outdoors at Prépinson'),('prepinson-indoor-riding-arena.webp','The bright indoor riding arena at Prépinson'),('prepinson-horse-handler-outdoors.webp','A horse and handler outdoors at Prépinson'),('prepinson-mare-and-foal.webp','A mare and foal at Prépinson'),('prepinson-show-jumping-training.webp','Show jumping training at Prépinson'),('prepinson-horses-green-paddocks.webp','Horses in the green paddocks at Prépinson')])+'</section>'
horses=horses.replace('<section id="breeding"',Path('src/programmes.html').read_text()+'<section id="breeding"')
page('horses','Haras de Prépinson — Horse Boarding & Young Horse Training in Belgium','Professional young horse training, show jumping, dressage and horse boarding at Haras de Prépinson in Belgium. Discover our breeding programme and horses for sale on Instagram.',horses.replace('/assets/estate-film.mp4','/assets/haras-film.mp4'),'Horses')
properties=[{'id':'ortho-24','title':'Ortho 24 – Grange','tag':'Space to gather. Room to unwind.','image':'prepinson-ortho-24-house-pool.webp','beds':4,'baths':4,'platform':'Casapilot','url':CASA,'description':'A generous Ardennes retreat, where stone walls meet contemporary comfort. Gather with family or friends, settle into slow mornings and make the most of the pool and outdoor hot tub.','amenities':['8 guests','4 bedrooms','4 bathrooms','Outdoor pool','Hot tub','Home cinema'],'gallery':[('grange-1.jpg','Ortho 24 Grange — stone exterior'),('grange-3.jpg','Ortho 24 Grange — living space'),('prepinson-ortho-24-bedroom.webp','Ortho 24 Grange — warm double bedroom'),('prepinson-ortho-24-kitchen.webp','Ortho 24 Grange — bright country kitchen'),('prepinson-ortho-24-hot-tub.webp','Ortho 24 Grange — outdoor hot tub'),('prepinson-ortho-24-billiards.webp','Ortho 24 Grange — billiards room')]},{'id':'ortho-25','title':'Ortho 25 – Cottage','tag':'Country character. A cosy escape.','image':'cottage.jpg','beds':3,'baths':3,'platform':'Airbnb','url':AIR,'description':'A welcoming stone cottage in the village of Ortho. With a private garden and space for eight, it is a lovely base for forest walks, unhurried lunches and time together in the Ardennes.','amenities':['8 guests','3 bedrooms','3 bathrooms','Private garden','Kitchen','2 parking spaces'],'gallery':[('cottage.jpg','Ortho 25 Cottage — stone exterior'),('cottage-1.jpg','Ortho 25 Cottage — welcoming living room'),('cottage-2.jpg','Ortho 25 Cottage — dining space'),('cottage-3.jpg','Ortho 25 Cottage — twin bedroom'),('prepinson-ortho-25-garden-terrace.webp','Ortho 25 Cottage — sunny garden terrace'),('prepinson-ortho-25-double-bedroom.webp','Ortho 25 Cottage — double bedroom')]}]
def property_card(p):
 return f'<article class="property-card"><a class="property-image" href="/houses/{p["id"]}/">{image(p["image"],p["title"])}</a><div class="property-info"><p class="eyebrow">{p["tag"]}</p><h3>{p["title"]}</h3><div class="property-meta"><span>8 guests</span><span>{p["beds"]} bedrooms</span><span>{p["baths"]} bathrooms</span></div><p>{p["description"]}</p><div class="property-links"><a class="btn dark" href="/houses/{p["id"]}/">Explore the house {ARROW}</a><a class="text-link" href="{p["url"]}" target="_blank" rel="noopener">{p["platform"]} {ARROW}</a></div></div></article>'
houses=hero('Stay at Prépinson','Make room<br><em>for slow living.</em>','Two beautiful homes. Your own corner of the Ardennes.',photo='prepinson-ortho-24-house-pool.webp',inner=True).replace('data-film="/assets/estate-film.mp4"','data-film="/assets/house-film.mp4"')
houses+='''<section id="discover" class="intro container"><div><p class="eyebrow">Our two houses</p><h2>Come together.<br><em>Feel at home.</em></h2></div><p class="body-copy">A weekend with friends. A few days with family. Choose your farmhouse escape in Belgium, with the countryside on your doorstep and La Roche-en-Ardenne a short drive away.</p></section>'''
houses+='<section class="property-grid container">'+''.join(property_card(p) for p in properties)+'</section>'
houses+=f'<section class="estate-section"><div class="estate-grid container"><div class="estate-photo">{image("prepinson-ortho-25-garden-terrace.webp","The sunny garden terrace at Ortho 25 Cottage")}</div><div class="estate-copy"><p class="eyebrow">Outside your door</p><h2>Less rush.<br><em>More Ardennes.</em></h2><p>Walk through the forests, explore La Roche-en-Ardenne or simply find a quiet spot in the garden. The best days here leave a little room for nothing at all.</p><button class="text-link" data-film="/assets/house-film.mp4">Watch life at the estate <span>▷</span></button></div></div></section>'
houses+=f'<section class="house-instagram"><div class="container"><div><p class="eyebrow">STAY A LITTLE LONGER</p><h2>The houses,<br><em>as they are lived.</em></h2></div><div><p>Seasonal details, new views and everyday moments from Ortho 24 and Ortho 25.</p><a class="editorial-link dark-link" href="{IG_HOUSE}" target="_blank" rel="noopener">@prepinson_the_house {ARROW}</a></div></div></section>'
page('houses','Prépinson Houses — Holiday Rentals in the Belgian Ardennes','Discover Ortho 24 Grange and Ortho 25 Cottage, two holiday homes for eight guests in Ortho, Belgium. Explore photos and book through Casapilot or Airbnb.',houses,'Houses')
for p in properties:
 name=p['title'].split(' – ')
 body=hero('Your Ardennes escape',name[0]+'.<br><em>The '+name[1]+'.</em>',p['tag'],photo=p['image'],inner=True,buttons=f'<a class="btn light" href="{p["url"]}" target="_blank" rel="noopener">Check availability on {p["platform"]} {ARROW}</a>').replace('data-film="/assets/estate-film.mp4"','data-film="/assets/house-film.mp4"')
 body+=f'<section id="discover" class="property-detail container"><div class="property-summary"><div><p class="eyebrow">{p["title"]} · Ortho, Belgium</p><h2>Your time.<br><em>Your place.</em></h2><p>{p["description"]}</p><div class="amenities">'+''.join(f'<span>{a}</span>' for a in p['amenities'])+f'</div><p>Near La Roche-en-Ardenne, in the heart of the Belgian Ardennes. Find the full amenities, house rules and current availability on {p["platform"]}.</p></div><aside class="booking-panel"><h3>Start planning your stay.</h3><p>See available dates, current prices and all the practical details on {p["platform"]}.</p><a class="btn dark" href="{p["url"]}" target="_blank" rel="noopener">Book with {p["platform"]} {ARROW}</a><p class="small-note" style="margin-top:20px;margin-bottom:0">A question before you book?<br><a class="text-link" href="mailto:thehouse@prepinson.com">Contact Prépinson {ARROW}</a></p></aside></div>'
 body+=gallery(p['gallery'])+'</section><section class="container" style="padding-bottom:65px"><a class="text-link" href="/houses/">← Explore both houses</a></section>'
 page('houses/'+p['id'],p['title']+' — Prépinson Holiday Home in Belgium',p['description'],body,'Houses')
OUT.joinpath('robots.txt').write_text('User-agent: *\nAllow: /\nSitemap: https://www.prepinson.com/sitemap.xml\n')
routes=['','horses/','houses/','houses/ortho-24/','houses/ortho-25/']
OUT.joinpath('sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join('<url><loc>https://www.prepinson.com/'+r+'</loc></url>' for r in routes)+'</urlset>')
# Property-specific structured data, readable without JavaScript.
for p in properties:
 f=OUT/'houses'/p['id']/'index.html'
 schema={'@context':'https://schema.org','@type':'VacationRental','name':p['title'],'identifier':'prepinson-'+p['id'],'url':'https://www.prepinson.com/houses/'+p['id']+'/','description':p['description'],'image':['https://www.prepinson.com/assets/'+n for n,a in p['gallery']],'address':{'@type':'PostalAddress','streetAddress':p['id'].replace('ortho-','Ortho '),'postalCode':'6983','addressLocality':'La Roche-en-Ardenne','addressCountry':'BE'},'containsPlace':{'@type':'Accommodation','occupancy':{'@type':'QuantitativeValue','value':8},'numberOfBedrooms':p['beds'],'numberOfBathroomsTotal':p['baths']},'sameAs':[p['url']]}
 f.write_text(f.read_text().replace('</head>','<script type="application/ld+json">'+json.dumps(schema)+'</script></head>'))
