"""Localized copy and routing context for the site forms.

This module deliberately stays separate from the editorial page data: form
labels and network states are a small, functional contract shared by every
template.
"""

LANGS = ("en", "fr", "nl", "de", "sv", "lb")

FORM_COPY = {
    "en": {
        "contact_eyebrow": "A shared passion starts a conversation.",
        "contact_title": "Let’s talk<br><em>about your plans.</em>",
        "contact_copy": "Tell us about your horse, your plans or the stay you have in mind. We will reply personally.",
        "contact_horses_copy": "Tell us about your horse and what you would like to work on. We will reply personally.",
        "contact_houses_copy": "Tell us about the stay you have in mind. We will reply personally.",
        "name": "Your name",
        "email": "Your email",
        "subject": "Subject",
        "message": "Your message",
        "privacy": "I have read the privacy information.",
        "send": "Send message",
        "sending": "Sending…",
        "server_error": "The message could not be sent. Please try again.",
        "network_error": "The connection was interrupted. Your entries have been kept; please try again.",
        "timeout_error": "The request took too long. Your entries have been kept; please try again.",
        "required_note": "All fields are required.",
        "trap": "Leave this field empty",
        "newsletter_title": "News from Prepinson",
        "newsletter_copy": "Horses, life at the haras and stays in the Ardennes.",
        "newsletter_email": "Your email address",
        "newsletter_consent": "I would like to receive news from Prepinson by email.",
        "newsletter_submit": "Subscribe",
        "newsletter_note": "Unsubscribe at any time.",
        "horses": "Horses",
        "houses": "Houses",
        "visit": "Visit",
        "legal": "Legal notice",
        "privacy_link": "Privacy",
        "haras_map": "Find the haras",
        "house_map": "Find the houses",
        "contact_success_title": "Thank you for your message.",
        "contact_success_copy": "Your request has been sent. The Prepinson team will reply personally.",
        "newsletter_success_title": "Thank you, your subscription has been recorded.",
        "newsletter_success_copy": "You are now subscribed to news from Prepinson.",
        "back": "Return to Prepinson",
        "film": "A film of Prepinson",
        "close_film": "Close film",
        "gallery": "Photo gallery",
        "close_gallery": "Close gallery",
        "previous": "Previous photograph",
        "next": "Next photograph",
    },
    "fr": {
        "contact_eyebrow": "UNE PASSION PARTAGÉE COMMENCE PAR UNE CONVERSATION.",
        "contact_title": "Parlons<br><em>de votre projet.</em>",
        "contact_copy": "Parlez-nous de votre cheval, de votre projet ou du séjour que vous envisagez. Nous vous répondrons personnellement.",
        "contact_horses_copy": "Parlez-nous de votre cheval et du travail que vous envisagez. Nous vous répondrons personnellement.",
        "contact_houses_copy": "Parlez-nous du séjour que vous envisagez. Nous vous répondrons personnellement.",
        "name": "Votre nom",
        "email": "Votre adresse e-mail",
        "subject": "Sujet",
        "message": "Votre message",
        "privacy": "J’ai pris connaissance des informations de confidentialité.",
        "send": "Envoyer le message",
        "sending": "Envoi en cours…",
        "server_error": "Le message n’a pas pu être envoyé. Veuillez réessayer.",
        "network_error": "La connexion a été interrompue. Votre saisie est conservée ; veuillez réessayer.",
        "timeout_error": "La demande a pris trop de temps. Votre saisie est conservée ; veuillez réessayer.",
        "required_note": "Tous les champs sont obligatoires.",
        "trap": "Laissez ce champ vide",
        "newsletter_title": "Les nouvelles de Prepinson",
        "newsletter_copy": "Chevaux, vie du haras et séjours dans les Ardennes.",
        "newsletter_email": "Votre adresse e-mail",
        "newsletter_consent": "Je souhaite recevoir par e-mail les nouvelles de Prepinson.",
        "newsletter_submit": "S’inscrire",
        "newsletter_note": "Désinscription à tout moment.",
        "horses": "Chevaux",
        "houses": "Maisons",
        "visit": "Adresse",
        "legal": "Mentions légales",
        "privacy_link": "Confidentialité",
        "haras_map": "Trouver le haras",
        "house_map": "Trouver les maisons",
        "contact_success_title": "Merci pour votre message.",
        "contact_success_copy": "Votre demande a bien été envoyée. L’équipe de Prepinson vous répondra personnellement.",
        "newsletter_success_title": "Merci, votre inscription a bien été enregistrée.",
        "newsletter_success_copy": "Vous êtes maintenant inscrit aux nouvelles de Prepinson.",
        "back": "Revenir à Prepinson",
        "film": "Un film de Prepinson",
        "close_film": "Fermer le film",
        "gallery": "Galerie photographique",
        "close_gallery": "Fermer la galerie",
        "previous": "Photographie précédente",
        "next": "Photographie suivante",
    },
    "nl": {
        "contact_eyebrow": "EEN GEDEELDE PASSIE BEGINT MET EEN GESPREK.",
        "contact_title": "Laten we praten<br><em>over uw plannen.</em>",
        "contact_copy": "Vertel ons over uw paard, uw plannen of het verblijf dat u voor ogen hebt. Wij antwoorden persoonlijk.",
        "contact_horses_copy": "Vertel ons over uw paard en waarmee u aan de slag wilt. Wij antwoorden persoonlijk.",
        "contact_houses_copy": "Vertel ons welk verblijf u voor ogen hebt. Wij antwoorden persoonlijk.",
        "name": "Uw naam",
        "email": "Uw e-mailadres",
        "subject": "Onderwerp",
        "message": "Uw bericht",
        "privacy": "Ik heb de privacyinformatie gelezen.",
        "send": "Bericht versturen",
        "sending": "Verzenden…",
        "server_error": "Het bericht kon niet worden verzonden. Probeer het opnieuw.",
        "network_error": "De verbinding werd onderbroken. Uw invoer is bewaard; probeer het opnieuw.",
        "timeout_error": "De aanvraag duurde te lang. Uw invoer is bewaard; probeer het opnieuw.",
        "required_note": "Alle velden zijn verplicht.",
        "trap": "Laat dit veld leeg",
        "newsletter_title": "Nieuws van Prepinson",
        "newsletter_copy": "Paarden, het leven op de haras en verblijven in de Ardennen.",
        "newsletter_email": "Uw e-mailadres",
        "newsletter_consent": "Ik wil nieuws van Prepinson per e-mail ontvangen.",
        "newsletter_submit": "Inschrijven",
        "newsletter_note": "Uitschrijven kan op elk moment.",
        "horses": "Paarden",
        "houses": "Huizen",
        "visit": "Bezoek",
        "legal": "Wettelijke vermeldingen",
        "privacy_link": "Privacy",
        "haras_map": "Vind de haras",
        "house_map": "Vind de huizen",
        "contact_success_title": "Bedankt voor uw bericht.",
        "contact_success_copy": "Uw aanvraag is verzonden. Het team van Prepinson antwoordt u persoonlijk.",
        "newsletter_success_title": "Bedankt, uw inschrijving is geregistreerd.",
        "newsletter_success_copy": "U bent nu ingeschreven voor nieuws van Prepinson.",
        "back": "Terug naar Prepinson",
        "film": "Een film van Prepinson",
        "close_film": "Film sluiten",
        "gallery": "Fotogalerij",
        "close_gallery": "Galerij sluiten",
        "previous": "Vorige foto",
        "next": "Volgende foto",
    },
    "de": {
        "contact_eyebrow": "GEMEINSAME LEIDENSCHAFT BEGINNT MIT EINEM GESPRÄCH.",
        "contact_title": "Sprechen wir<br><em>über Ihre Pläne.</em>",
        "contact_copy": "Erzählen Sie uns von Ihrem Pferd, Ihren Plänen oder Ihrem gewünschten Aufenthalt. Wir antworten persönlich.",
        "contact_horses_copy": "Erzählen Sie uns von Ihrem Pferd und woran Sie arbeiten möchten. Wir antworten persönlich.",
        "contact_houses_copy": "Erzählen Sie uns von Ihrem gewünschten Aufenthalt. Wir antworten persönlich.",
        "name": "Ihr Name",
        "email": "Ihre E-Mail-Adresse",
        "subject": "Betreff",
        "message": "Ihre Nachricht",
        "privacy": "Ich habe die Datenschutzinformationen gelesen.",
        "send": "Nachricht senden",
        "sending": "Wird gesendet…",
        "server_error": "Die Nachricht konnte nicht gesendet werden. Bitte versuchen Sie es erneut.",
        "network_error": "Die Verbindung wurde unterbrochen. Ihre Eingaben bleiben erhalten; bitte versuchen Sie es erneut.",
        "timeout_error": "Die Anfrage hat zu lange gedauert. Ihre Eingaben bleiben erhalten; bitte versuchen Sie es erneut.",
        "required_note": "Alle Felder sind Pflichtfelder.",
        "trap": "Lassen Sie dieses Feld leer",
        "newsletter_title": "Neuigkeiten aus Prepinson",
        "newsletter_copy": "Pferde, das Leben auf dem Haras und Aufenthalte in den Ardennen.",
        "newsletter_email": "Ihre E-Mail-Adresse",
        "newsletter_consent": "Ich möchte die Neuigkeiten von Prepinson per E-Mail erhalten.",
        "newsletter_submit": "Anmelden",
        "newsletter_note": "Abmeldung jederzeit möglich.",
        "horses": "Pferde",
        "houses": "Ferienhäuser",
        "visit": "Adresse",
        "legal": "Impressum",
        "privacy_link": "Datenschutz",
        "haras_map": "Haras finden",
        "house_map": "Ferienhäuser finden",
        "contact_success_title": "Vielen Dank für Ihre Nachricht.",
        "contact_success_copy": "Ihre Anfrage wurde gesendet. Das Team von Prepinson antwortet Ihnen persönlich.",
        "newsletter_success_title": "Vielen Dank, Ihre Anmeldung wurde registriert.",
        "newsletter_success_copy": "Sie erhalten jetzt die Neuigkeiten von Prepinson.",
        "back": "Zurück zu Prepinson",
        "film": "Ein Film über Prepinson",
        "close_film": "Film schließen",
        "gallery": "Fotogalerie",
        "close_gallery": "Galerie schließen",
        "previous": "Vorheriges Foto",
        "next": "Nächstes Foto",
    },
    "sv": {
        "contact_eyebrow": "EN GEMENSAM PASSION BÖRJAR MED ETT SAMTAL.",
        "contact_title": "Låt oss prata<br><em>om dina planer.</em>",
        "contact_copy": "Berätta om din häst, dina planer eller vistelsen du har i åtanke. Vi svarar personligen.",
        "contact_horses_copy": "Berätta om din häst och vad du vill arbeta med. Vi svarar personligen.",
        "contact_houses_copy": "Berätta om vistelsen du har i åtanke. Vi svarar personligen.",
        "name": "Ditt namn",
        "email": "Din e-postadress",
        "subject": "Ämne",
        "message": "Ditt meddelande",
        "privacy": "Jag har läst integritetsinformationen.",
        "send": "Skicka meddelande",
        "sending": "Skickar…",
        "server_error": "Meddelandet kunde inte skickas. Försök igen.",
        "network_error": "Anslutningen avbröts. Dina uppgifter har sparats; försök igen.",
        "timeout_error": "Förfrågan tog för lång tid. Dina uppgifter har sparats; försök igen.",
        "required_note": "Alla fält är obligatoriska.",
        "trap": "Lämna detta fält tomt",
        "newsletter_title": "Nyheter från Prepinson",
        "newsletter_copy": "Hästar, livet på haras och vistelser i Ardennerna.",
        "newsletter_email": "Din e-postadress",
        "newsletter_consent": "Jag vill få nyheter från Prepinson via e-post.",
        "newsletter_submit": "Prenumerera",
        "newsletter_note": "Avsluta prenumerationen när som helst.",
        "horses": "Hästar",
        "houses": "Hus",
        "visit": "Besök",
        "legal": "Juridisk information",
        "privacy_link": "Integritet",
        "haras_map": "Hitta till haras",
        "house_map": "Hitta till husen",
        "contact_success_title": "Tack för ditt meddelande.",
        "contact_success_copy": "Din förfrågan har skickats. Teamet på Prepinson svarar dig personligen.",
        "newsletter_success_title": "Tack, din prenumeration har registrerats.",
        "newsletter_success_copy": "Du prenumererar nu på nyheter från Prepinson.",
        "back": "Tillbaka till Prepinson",
        "film": "En film om Prepinson",
        "close_film": "Stäng filmen",
        "gallery": "Fotogalleri",
        "close_gallery": "Stäng galleriet",
        "previous": "Föregående bild",
        "next": "Nästa bild",
    },
    "lb": {
        "contact_eyebrow": "ENG GEMEINSAM PASSIOUN FÄNKT MAT ENGEM GESPRÉICH UN.",
        "contact_title": "Loosst eis<br><em>iwwer Äre Projet schwätzen.</em>",
        "contact_copy": "Erzielt eis vun Ärem Päerd, Äre Pläng oder dem Openthalt, deen Dir am Kapp hutt. Mir äntweren Iech perséinlech.",
        "contact_horses_copy": "Erzielt eis vun Ärem Päerd a wat Dir wëllt schaffen. Mir äntweren Iech perséinlech.",
        "contact_houses_copy": "Erzielt eis vum Openthalt, deen Dir am Kapp hutt. Mir äntweren Iech perséinlech.",
        "name": "Ären Numm",
        "email": "Är E-Mail-Adress",
        "subject": "Sujet",
        "message": "Äre Message",
        "privacy": "Ech hunn d’Dateschutzinformatioune gelies.",
        "send": "Message schécken",
        "sending": "Gëtt geschéckt…",
        "server_error": "De Message konnt net geschéckt ginn. Probéiert w.e.g. nach eng Kéier.",
        "network_error": "D’Verbindung gouf ënnerbrach. Är Donnéeë sinn erhale bliwwen; probéiert w.e.g. nach eng Kéier.",
        "timeout_error": "D’Ufro huet ze laang gedauert. Är Donnéeë sinn erhale bliwwen; probéiert w.e.g. nach eng Kéier.",
        "required_note": "All Felder sinn obligatoresch.",
        "trap": "Loosst dëst Feld eidel",
        "newsletter_title": "Neiegkeete vu Prepinson",
        "newsletter_copy": "Päerd, d’Liewen um Haras an Openthalter an den Ardennen.",
        "newsletter_email": "Är E-Mail-Adress",
        "newsletter_consent": "Ech wëll d’Neiegkeete vu Prepinson per E-Mail kréien.",
        "newsletter_submit": "Umellen",
        "newsletter_note": "Ofmeldung zu all Moment.",
        "horses": "Päerd",
        "houses": "Haiser",
        "visit": "Adress",
        "legal": "Impressum",
        "privacy_link": "Dateschutz",
        "haras_map": "Den Haras fannen",
        "house_map": "D’Haiser fannen",
        "contact_success_title": "Merci fir Äre Message.",
        "contact_success_copy": "Är Ufro gouf geschéckt. D’Ekipp vu Prepinson äntwert Iech perséinlech.",
        "newsletter_success_title": "Merci, Är Umeldung gouf registréiert.",
        "newsletter_success_copy": "Dir kritt elo d’Neiegkeete vu Prepinson.",
        "back": "Zeréck op Prepinson",
        "film": "E Film iwwer Prepinson",
        "close_film": "Film zoumaachen",
        "gallery": "Fotogalerie",
        "close_gallery": "Galerie zoumaachen",
        "previous": "Viregt Bild",
        "next": "Nächst Bild",
    },
}

SUBJECTS = {
    "en": (("boarding", "Horse boarding"), ("training", "Horse training"), ("breeding", "Breeding"), ("programme-foal", "Programme — Foal handling"), ("programme-pre-breaking", "Programme — Pre-breaking"), ("programme-breaking", "Programme — Breaking-in"), ("programme-jumping", "Programme — Show jumping training"), ("horse-search", "Looking for a horse"), ("stay", "A stay at Prepinson"), ("ortho-24", "A stay at Ortho 24 — La Grange"), ("ortho-25", "A stay at Ortho 25 — Le Cottage"), ("other", "Another request")),
    "fr": (("boarding", "Pension"), ("training", "Travail des chevaux"), ("breeding", "Élevage"), ("programme-foal", "Programme — Manipulation du poulain"), ("programme-pre-breaking", "Programme — Pré-débourrage"), ("programme-breaking", "Programme — Débourrage"), ("programme-jumping", "Programme — Entraînement au saut d’obstacles"), ("horse-search", "Recherche d’un cheval"), ("stay", "Un séjour à Prepinson"), ("ortho-24", "Un séjour à Ortho 24 — La Grange"), ("ortho-25", "Un séjour à Ortho 25 — Le Cottage"), ("other", "Autre demande")),
    "nl": (("boarding", "Paardenpension"), ("training", "Training van paarden"), ("breeding", "Fokkerij"), ("programme-foal", "Programma — Veulenbegeleiding"), ("programme-pre-breaking", "Programma — Voorbereiding op zadelmak maken"), ("programme-breaking", "Programma — Zadelmak maken"), ("programme-jumping", "Programma — Springtraining"), ("horse-search", "Een paard zoeken"), ("stay", "Een verblijf bij Prepinson"), ("ortho-24", "Een verblijf in Ortho 24 — La Grange"), ("ortho-25", "Een verblijf in Ortho 25 — Le Cottage"), ("other", "Andere vraag")),
    "de": (("boarding", "Pferdepension"), ("training", "Pferdeausbildung"), ("breeding", "Zucht"), ("programme-foal", "Programm — Fohlenhandling"), ("programme-pre-breaking", "Programm — Vorbereitung auf das Anreiten"), ("programme-breaking", "Programm — Anreiten"), ("programme-jumping", "Programm — Springtraining"), ("horse-search", "Suche nach einem Pferd"), ("stay", "Ein Aufenthalt bei Prepinson"), ("ortho-24", "Ein Aufenthalt in Ortho 24 — La Grange"), ("ortho-25", "Ein Aufenthalt in Ortho 25 — Le Cottage"), ("other", "Andere Anfrage")),
    "sv": (("boarding", "Hästuppstallning"), ("training", "Hästträning"), ("breeding", "Avel"), ("programme-foal", "Program — Fölhantering"), ("programme-pre-breaking", "Program — Förberedelse för inridning"), ("programme-breaking", "Program — Inridning"), ("programme-jumping", "Program — Hoppträning"), ("horse-search", "Söker en häst"), ("stay", "En vistelse på Prepinson"), ("ortho-24", "En vistelse i Ortho 24 — La Grange"), ("ortho-25", "En vistelse i Ortho 25 — Le Cottage"), ("other", "Annan förfrågan")),
    "lb": (("boarding", "Päerdspensioun"), ("training", "Ausbildung vu Päerd"), ("breeding", "Zuucht"), ("programme-foal", "Programm — Ëmgang mam Fëllen"), ("programme-pre-breaking", "Programm — Virbereedung op d’Ureiden"), ("programme-breaking", "Programm — Ureiden"), ("programme-jumping", "Programm — Sprangtraining"), ("horse-search", "Sich no engem Päerd"), ("stay", "En Openthalt zu Prepinson"), ("ortho-24", "En Openthalt am Ortho 24 — La Grange"), ("ortho-25", "En Openthalt am Ortho 25 — Le Cottage"), ("other", "Aner Ufro")),
}
