"""Publisher verified against BCE Public Search on 2026-09-30.
Retention periods are Prepinson's operating policy, not statutory universal limits.
"""
COPY = {
 'legal_company': ('Publisher and publication responsibility','Éditeur et responsable de publication','Uitgever en publicatieverantwoordelijke','Herausgeber und Publikationsverantwortung','Utgivare och publiceringsansvar','Editeur a Publikatiounsverantwortung'),
 'legal_creator': ('Website design and development','Conception et réalisation du site','Ontwerp en ontwikkeling','Konzeption und Umsetzung','Design och utveckling','Konzept an Ëmsetzung'),
 'legal_registration': ('Company register / VAT','BCE / TVA','KBO / btw','Unternehmensnummer / USt.','Företagsnummer / moms','Entreprise / TVA'),
 'privacy_controller': ('Data controller','Responsable du traitement','Verwerkingsverantwoordelijke','Verantwortlicher','Personuppgiftsansvarig','Responsabele fir d’Veraarbechtung'),
 'privacy_retention': ('Retention periods','Durées de conservation','Bewaartermijnen','Speicherdauer','Lagringstider','Späicherdauer'),
 'privacy_retention_copy': (
  'Enquiries that do not lead to a contract are kept for up to 24 months after the last exchange, then deleted. Newsletter data is kept until you withdraw your consent, or for up to 24 months without an active interaction from you. If a contract is concluded, records needed for accounting, legal obligations or a dispute are retained separately for the applicable period, with restricted access.',
  'Les demandes sans suite contractuelle sont conservées au maximum 24 mois après le dernier échange, puis supprimées. Les données de newsletter sont conservées jusqu’au retrait de votre consentement, ou au maximum 24 mois sans interaction active de votre part. En cas de contrat, les pièces nécessaires à la comptabilité, aux obligations légales ou à un litige sont conservées séparément pendant la durée applicable, avec un accès restreint.',
  'Aanvragen die niet tot een overeenkomst leiden, worden maximaal 24 maanden na het laatste contact bewaard en daarna verwijderd. Nieuwsbriefgegevens worden bewaard tot u uw toestemming intrekt, of maximaal 24 maanden zonder actieve interactie van u. Bij een overeenkomst worden documenten voor boekhouding, wettelijke verplichtingen of een geschil afzonderlijk bewaard gedurende de toepasselijke termijn, met beperkte toegang.',
  'Anfragen ohne Vertragsabschluss werden höchstens 24 Monate nach dem letzten Austausch gespeichert und anschließend gelöscht. Newsletter-Daten bleiben bis zum Widerruf Ihrer Einwilligung oder höchstens 24 Monate ohne aktive Interaktion Ihrerseits gespeichert. Bei einem Vertrag werden Unterlagen für Buchhaltung, gesetzliche Pflichten oder Streitfälle getrennt für die geltende Dauer und mit beschränktem Zugang aufbewahrt.',
  'Förfrågningar som inte leder till avtal sparas högst 24 månader efter den senaste kontakten och raderas sedan. Nyhetsbrevsuppgifter sparas tills du återkallar ditt samtycke, eller högst 24 månader utan aktiv kontakt från dig. Vid avtal sparas handlingar för bokföring, rättsliga skyldigheter eller tvister separat under tillämplig tid med begränsad åtkomst.',
  'Ufroen ouni Kontrakt ginn héchstens 24 Méint nom leschten Austausch gespäichert an duerno geläscht. Newsletter-Donnéeë gi bis zum Réckzuch vun Ärer Zoustëmmung oder héchstens 24 Méint ouni aktiv Interaktioun vun Iech gespäichert. Bei engem Kontrakt gi Beleeër fir d’Comptabilitéit, gesetzlech Flichten oder e Sträit getrennt fir déi uwendbar Dauer a mat limitéiertem Zougang versuergt.'),
 'privacy_basis_copy': (
  'We use your contact details to handle your request: steps at your request before a contract (Article 6(1)(b) GDPR) or our legitimate interest in responding to general enquiries (Article 6(1)(f)). Required fields are needed to reply; without them the form cannot be sent. Newsletter delivery relies on your separate consent (Article 6(1)(a)). Contacting us never subscribes you to the newsletter. We do not profile visitors or make automated decisions about them.',
  'Vos coordonnées servent à traiter votre demande : mesures précontractuelles prises à votre demande (article 6.1.b du RGPD) ou intérêt légitime à répondre aux questions générales (article 6.1.f). Les champs obligatoires sont nécessaires pour vous répondre ; sans eux, le formulaire ne peut être envoyé. La newsletter repose sur votre consentement distinct (article 6.1.a). Nous contacter ne vous inscrit jamais à la newsletter. Nous ne réalisons ni profilage ni décision automatisée concernant les visiteurs.',
  'Wij gebruiken uw contactgegevens voor uw aanvraag: stappen op uw verzoek vóór een overeenkomst (artikel 6.1.b AVG) of ons gerechtvaardigd belang om algemene vragen te beantwoorden (artikel 6.1.f). Verplichte velden zijn nodig om te antwoorden; zonder deze kan het formulier niet worden verzonden. De nieuwsbrief berust op afzonderlijke toestemming (artikel 6.1.a). Contact opnemen leidt nooit tot inschrijving voor de nieuwsbrief. Wij maken geen profielen en nemen geen geautomatiseerde besluiten over bezoekers.',
  'Ihre Kontaktdaten dienen Ihrer Anfrage: vorvertragliche Maßnahmen auf Ihren Wunsch (Art. 6 Abs. 1 b DSGVO) oder unser berechtigtes Interesse an der Beantwortung allgemeiner Fragen (Art. 6 Abs. 1 f). Pflichtfelder werden für die Antwort benötigt; ohne sie kann das Formular nicht gesendet werden. Der Newsletter beruht auf gesonderter Einwilligung (Art. 6 Abs. 1 a). Eine Kontaktaufnahme führt nie zur Newsletter-Anmeldung. Wir erstellen keine Besucherprofile und treffen keine automatisierten Entscheidungen über Besucher.',
  'Kontaktuppgifter används för din förfrågan: åtgärder på din begäran inför ett avtal (artikel 6.1 b GDPR) eller vårt berättigade intresse av att besvara allmänna frågor (artikel 6.1 f). Obligatoriska fält behövs för att svara; utan dem kan formuläret inte skickas. Nyhetsbrevet bygger på separat samtycke (artikel 6.1 a). Att kontakta oss innebär aldrig att du anmäls till nyhetsbrevet. Vi profilerar inte besökare och fattar inga automatiserade beslut om dem.',
  'Är Kontaktdonnéeë déngen Ärer Ufro: Schrëtt op Äre Wonsch virun engem Kontrakt (Artikel 6.1.b RGPD) oder eisen legitimmen Interessi, allgemeng Froen ze beäntweren (Artikel 6.1.f). Obligatoresch Felder gi fir d’Äntwert gebraucht; ouni si kann de Formular net geschéckt ginn. Den Newsletter baséiert op enger separater Zoustëmmung (Artikel 6.1.a). Eng Kontaktufro mellt Iech ni fir den Newsletter un. Mir erstellen keng Visiteursprofiller an huele keng automatiséiert Decisiounen iwwer Visiteuren.'),
 'privacy_rights_copy': (
  'You can request access, correction, deletion, restriction or portability of your data, where applicable, and object to processing based on legitimate interests. Withdraw newsletter consent at any time, without affecting earlier lawful processing, by writing to haras@prepinson.com. We respond normally within one month. You may also complain to the Belgian Data Protection Authority.',
  'Vous pouvez demander l’accès, la rectification, l’effacement, la limitation ou la portabilité de vos données lorsque ces droits s’appliquent, et vous opposer aux traitements fondés sur l’intérêt légitime. Retirez à tout moment votre consentement à la newsletter, sans effet sur la licéité des traitements antérieurs, en écrivant à haras@prepinson.com. Nous répondons normalement sous un mois. Vous pouvez aussi introduire une réclamation auprès de l’Autorité belge de protection des données.',
  'U kunt, waar van toepassing, inzage, correctie, verwijdering, beperking of overdraagbaarheid van uw gegevens vragen en bezwaar maken tegen verwerking op basis van gerechtvaardigd belang. Trek uw nieuwsbrief-toestemming op elk moment in via haras@prepinson.com, zonder gevolgen voor eerdere rechtmatige verwerking. Wij antwoorden normaal binnen een maand. U kunt ook een klacht indienen bij de Belgische Gegevensbeschermingsautoriteit.',
  'Sie können gegebenenfalls Auskunft, Berichtigung, Löschung, Einschränkung oder Übertragbarkeit Ihrer Daten verlangen und einer Verarbeitung aufgrund berechtigter Interessen widersprechen. Widerrufen Sie Ihre Newsletter-Einwilligung jederzeit über haras@prepinson.com; die bisherige rechtmäßige Verarbeitung bleibt unberührt. Wir antworten normalerweise innerhalb eines Monats. Sie können sich auch bei der belgischen Datenschutzbehörde beschweren.',
  'Du kan i tillämpliga fall begära tillgång, rättelse, radering, begränsning eller överföring av dina uppgifter och invända mot behandling grundad på berättigat intresse. Återkalla när som helst ditt samtycke till nyhetsbrevet via haras@prepinson.com, utan att det påverkar tidigare laglig behandling. Vi svarar normalt inom en månad. Du kan också klaga hos den belgiska dataskyddsmyndigheten.',
  'Dir kënnt, wou uwendbar, Zougang, Verbesserung, Läschung, Aschränkung oder Portabilitéit vun Ären Donnéeë froen an der Veraarbechtung op Basis vum legitimmen Interessi widderspriechen. Zitt Är Newsletter-Zoustëmmung zu all Moment iwwer haras@prepinson.com zréck; déi viregt rechtméisseg Veraarbechtung bleift onberéiert. Mir äntweren normalerweis bannent engem Mount. Dir kënnt och eng Plainte bei der belscher Dateschutzautoritéit maachen.'),
 'privacy_transfers': ('Access and international transfers','Accès et transferts internationaux','Toegang en internationale doorgifte','Zugang und internationale Übermittlungen','Åtkomst och internationella överföringar','Zougang an international Transferten'),
 'privacy_transfers_copy': (
  'Only authorised Prepinson staff and service providers acting on its instructions can access form data. Netlify may process it outside the European Economic Area, including in the United States. Its data processing agreement provides transfer safeguards, including European Commission standard contractual clauses. Hosting security logs can include IP addresses and technical request information. No visitor analytics or advertising tracking is added to this site.',
  'Seules les personnes habilitées de Prepinson et les prestataires agissant sur ses instructions peuvent accéder aux données des formulaires. Netlify peut les traiter hors de l’Espace économique européen, notamment aux États-Unis. Son accord de traitement prévoit des garanties de transfert, dont les clauses contractuelles types de la Commission européenne. Les journaux de sécurité de l’hébergeur peuvent inclure l’adresse IP et des informations techniques de requête. Aucun outil de suivi publicitaire ou d’analyse individuelle des visiteurs n’est ajouté au site.',
  'Alleen bevoegde medewerkers van Prepinson en dienstverleners die volgens zijn instructies handelen, hebben toegang tot formuliergegevens. Netlify kan deze buiten de Europese Economische Ruimte verwerken, waaronder in de Verenigde Staten. De verwerkersovereenkomst bevat waarborgen voor doorgifte, waaronder standaardcontractbepalingen van de Europese Commissie. Beveiligingslogs van de hosting kunnen IP-adressen en technische verzoekgegevens bevatten. De site voegt geen bezoekersanalyse of advertentietracking toe.',
  'Nur befugte Mitarbeitende von Prepinson und weisungsgebundene Dienstleister können auf Formulardaten zugreifen. Netlify kann diese außerhalb des Europäischen Wirtschaftsraums, etwa in den USA, verarbeiten. Die Datenverarbeitungsvereinbarung enthält Übermittlungsgarantien einschließlich der Standardvertragsklauseln der Europäischen Kommission. Sicherheitsprotokolle des Hosters können IP-Adressen und technische Anfragedaten enthalten. Die Website ergänzt keine Besucheranalyse oder Werbeverfolgung.',
  'Endast behörig personal hos Prepinson och tjänsteleverantörer som följer dess instruktioner har tillgång till formuläruppgifter. Netlify kan behandla dem utanför Europeiska ekonomiska samarbetsområdet, bland annat i USA. Personuppgiftsbiträdesavtalet innehåller skydd för överföringar, bland annat EU-kommissionens standardavtalsklausuler. Säkerhetsloggar hos webbhotellet kan innehålla IP-adresser och tekniska uppgifter om anrop. Webbplatsen lägger inte till besökaranalys eller annonsspårning.',
  'Nëmme befugte Mataarbechter vu Prepinson an Déngschtleeschter, déi seng Instruktioune befollegen, kréien Zougang zu de Formulardonnéeën. Netlify kann dës ausserhalb vum Europäesche Wirtschaftsraum verschaffen, och an den USA. Säin Dateschutzaccord gesäit Garantien fir Transferten vir, dorënner d’Standardvertragsklauselen vun der Europäescher Kommissioun. Sécherheetsprotokoller vum Hoster kënnen IP-Adressen an technesch Ufroinformatiounen enthalen. D’Websäit füügt keng Visiteursanalyse oder Reklammeverfolgung bäi.'),
 'privacy_external': ('Booking and external services','Réservations et services externes','Boekingen en externe diensten','Buchung und externe Dienste','Bokning och externa tjänster','Reservatiounen an extern Servicer'),
 'privacy_external_copy': (
  'Bookings are made on the linked platforms, under their own conditions and privacy policies. Maps, Instagram and booking platforms are not embedded: they only receive a visit when you follow an external link.',
  'Les réservations sont effectuées sur les plateformes liées, selon leurs propres conditions et politiques de confidentialité. Les cartes, Instagram et les plateformes de réservation ne sont pas intégrés : ils ne reçoivent votre visite que si vous suivez un lien externe.',
  'Boekingen verlopen via de gelinkte platforms, volgens hun eigen voorwaarden en privacybeleid. Kaarten, Instagram en boekingsplatforms zijn niet ingebed: zij ontvangen alleen een bezoek als u een externe link volgt.',
  'Buchungen erfolgen über die verlinkten Plattformen nach deren eigenen Bedingungen und Datenschutzhinweisen. Karten, Instagram und Buchungsplattformen sind nicht eingebettet: Sie erhalten erst bei einem externen Linkaufruf Ihren Besuch.',
  'Bokningar görs på de länkade plattformarna enligt deras egna villkor och integritetspolicyer. Kartor, Instagram och bokningsplattformar är inte inbäddade: de får bara ett besök när du följer en extern länk.',
  'Reservatioune ginn op de verlinkte Plattformen ënner hiren eegene Konditiounen an Dateschutzreegele gemaach. Kaarten, Instagram a Buchungsplattforme sinn net agebonnen: si kréien Äre Besuch eréischt, wann Dir engem externe Link nogitt.'),
}
