"""Presentation-only labels and media assignments for the V1 interface.

Editorial copy and metadata remain in :mod:`src.site_data`.  This module only
contains short interface labels, verified links, and the approved media map.
"""

from src.site_data import LANGS


def _l(en, fr, nl, de, sv, lb):
    return dict(zip(LANGS, (en, fr, nl, de, sv, lb)))


UI = {
    "nav_haras": _l("The stud farm", "Le haras", "De stoeterij", "Das Gestüt", "Stuteriet", "D’Gestitt"),
    "nav_expertise": _l("Our expertise", "Notre savoir-faire", "Onze expertise", "Unser Können", "Vår expertis", "Eist Kënnen"),
    "nav_journal": _l("Journal", "Journal", "Journaal", "Journal", "Journal", "Journal"),
    "hero_cta": _l("Discover our work", "Découvrir nos activités", "Ontdek ons werk", "Unsere Arbeit entdecken", "Upptäck vårt arbete", "Eis Aarbecht entdecken"),
    "watch_film": _l("Watch the film", "Voir le film", "Bekijk de film", "Film ansehen", "Se filmen", "Film kucken"),
    "scroll": _l("Scroll to explore", "Poursuivre la visite", "Verder ontdekken", "Weiter entdecken", "Fortsätt upptäcka", "Weider entdecken"),
    "location": _l("Ortho, Belgian Ardennes", "Ortho, Ardennes belges", "Ortho, Belgische Ardennen", "Ortho, Belgische Ardennen", "Ortho, belgiska Ardennerna", "Ortho, belsch Ardennen"),
    "intro_label": _l("The haras", "Le haras", "De stoeterij", "Das Gestüt", "Stuteriet", "De Gestüt"),
    "intro_note": _l("Trust is where it all begins.", "Tout commence par la confiance.", "Alles begint met vertrouwen.", "Alles beginnt mit Vertrauen.", "Allt börjar med tillit.", "Alles fänkt mat Vertrauen un."),
    "expertise_label": _l("Our expertise", "Notre savoir-faire", "Onze expertise", "Unser Können", "Vår expertis", "Eist Kënnen"),
    "expertise_title": _l("The care behind the potential.", "Les soins au service du potentiel.", "Zorg die potentieel laat groeien.", "Fürsorge, die Potenzial entfaltet.", "Omsorg som utvecklar potential.", "Betreiung, déi Potenzial entwéckelt."),
    "expertise_intro": _l("From the first steps to the next chapter. A considered approach at every stage.", "Des premiers pas au prochain chapitre. Une approche réfléchie à chaque étape.", "Van de eerste stappen tot het volgende hoofdstuk. Een doordachte aanpak in elke fase.", "Von den ersten Schritten bis zum nächsten Kapitel. Ein durchdachter Ansatz in jeder Phase.", "Från de första stegen till nästa kapitel. Ett genomtänkt arbetssätt i varje fas.", "Vun den éischte Schrëtt bis zum nächste Kapitel. Eng duerchduecht Approche an all Phas."),
    "breeding_title": _l("Breeding & young horses", "Élevage & jeunes chevaux", "Fokkerij & jonge paarden", "Zucht & Jungpferde", "Avel & unghästar", "Zuucht & jonk Päerd"),
    "facilities_cta": _l("Discover the facilities", "Découvrir les installations", "Ontdek de faciliteiten", "Anlage entdecken", "Upptäck anläggningen", "Infrastrukturen entdecken"),
    "references_label": _l("Born at Prepinson", "Nés à Prepinson", "Geboren bij Prepinson", "In Prepinson geboren", "Födda på Prepinson", "Zu Prepinson gebuer"),
    "team_label": _l("The people of Prepinson", "L’équipe de Prepinson", "Het team van Prepinson", "Das Team von Prepinson", "Teamet på Prepinson", "D'Ekipp vu Prepinson"),
    "team_title": _l("Experience, instinct and daily care.", "Expérience, instinct et soins quotidiens.", "Ervaring, instinct en dagelijkse zorg.", "Erfahrung, Gespür und tägliche Fürsorge.", "Erfarenhet, känsla och daglig omsorg.", "Erfarung, Instinkt an deeglech Betreiung."),
    "team_intro": _l("A small, committed team gives every horse individual attention, patience and the right environment.", "Une équipe engagée apporte à chaque cheval une attention individuelle, de la patience et un environnement adapté.", "Een betrokken team geeft elk paard individuele aandacht, geduld en de juiste omgeving.", "Ein engagiertes Team schenkt jedem Pferd individuelle Aufmerksamkeit, Geduld und das passende Umfeld.", "Ett engagerat team ger varje häst individuell uppmärksamhet, tålamod och rätt miljö.", "Eng engagéiert Ekipp gëtt all Päerd individuell Opmierksamkeet, Gedold an dat passend Ëmfeld."),
    "eva_role": _l("Manager & founder", "Gérante & fondatrice", "Manager & oprichter", "Leitung & Gründerin", "Chef & grundare", "Gerante & Grënnerin"),
    "nicolas_role": _l("Site manager", "Responsable du site", "Locatiemanager", "Betriebsleiter", "Platsansvarig", "Responsabele vum Site"),
    "houses_label": _l("Stay at Prepinson", "Séjourner à Prepinson", "Verblijven bij Prepinson", "Aufenthalt in Prepinson", "Bo på Prepinson", "Zu Prepinson bleiwen"),
    "houses_home_copy": _l("Two houses in the heart of the Ardennes, for enjoying the estate and its surroundings.", "Deux maisons au cœur des Ardennes, pour profiter du domaine et de ses environs.", "Twee huizen in het hart van de Ardennen, om van het domein en de omgeving te genieten.", "Zwei Häuser im Herzen der Ardennen, um das Anwesen und seine Umgebung zu genießen.", "Två hus i hjärtat av Ardennerna, för att njuta av gården och omgivningarna.", "Zwee Haiser am Häerz vun den Ardennen, fir d'Domaine an d'Ëmgéigend ze genéissen."),
    "houses_cta": _l("Discover the houses", "Découvrir les maisons", "Ontdek de huizen", "Häuser entdecken", "Upptäck husen", "D'Haiser entdecken"),
    "journal_label": _l("Notes from Prepinson", "Le journal de Prepinson", "Notities uit Prepinson", "Notizen aus Prepinson", "Anteckningar från Prepinson", "Notize vu Prepinson"),
    "official_link": _l("Official website", "Site officiel", "Officiële website", "Offizielle Website", "Officiell webbplats", "Offiziell Websäit"),
    "check_availability": _l("Check availability", "Consulter les disponibilités", "Beschikbaarheid bekijken", "Verfügbarkeit prüfen", "Se tillgänglighet", "Disponibilitéit kucken"),
    "book_casapilot": _l("Check availability on Casapilot", "Voir les disponibilités sur Casapilot", "Bekijk beschikbaarheid op Casapilot", "Verfügbarkeit auf Casapilot prüfen", "Se tillgänglighet på Casapilot", "Disponibilitéit op Casapilot kucken"),
    "book_airbnb": _l("Check availability on Airbnb", "Voir les disponibilités sur Airbnb", "Bekijk beschikbaarheid op Airbnb", "Verfügbarkeit auf Airbnb prüfen", "Se tillgänglighet på Airbnb", "Disponibilitéit op Airbnb kucken"),
    "other_house": _l("Discover the other house", "Découvrir l’autre maison", "Ontdek het andere huis", "Das andere Haus entdecken", "Upptäck det andra huset", "Dat anert Haus entdecken"),
    "activities_cta": _l("Explore the surroundings", "Découvrir les environs", "Ontdek de omgeving", "Umgebung entdecken", "Upptäck omgivningarna", "D'Ëmgéigend entdecken"),
    "activities_guide_label": _l("A local guide", "Guide local", "Lokale gids", "Lokaler Guide", "Lokal guide", "Lokale Guide"),
    "activities_guide_title": _l("Days out from Ortho.", "Que faire autour d’Ortho ?", "Op pad vanuit Ortho.", "Ausflüge rund um Ortho.", "Utflykter runt Ortho.", "Ausflich ronderëm Ortho."),
    "activities_guide_intro": _l(
        "Walks, cycling routes, water activities and places to visit from your base in the Belgian Ardennes. Each recommendation links to its official source for current practical information.",
        "Promenades, itinéraires à vélo, activités sur l’eau et lieux à visiter depuis Ortho. Chaque suggestion renvoie vers sa source officielle pour les informations pratiques à jour.",
        "Wandelingen, fietsroutes, wateractiviteiten en bezienswaardigheden vanuit Ortho. Elke suggestie verwijst naar de officiële bron voor actuele praktische informatie.",
        "Wanderungen, Radtouren, Aktivitäten am Wasser und Ausflugsziele rund um Ortho. Jede Empfehlung führt zur offiziellen Quelle mit aktuellen praktischen Informationen.",
        "Vandringar, cykelturer, vattenaktiviteter och utflyktsmål med Ortho som utgångspunkt. Varje tips länkar till den officiella källan för aktuell praktisk information.",
        "Wanderungen, Vëlosweeër, Waasseraktivitéiten an Ausfluchsziler vun Ortho aus. All Tipp féiert bei déi offiziell Quell mat den aktuelle prakteschen Informatiounen.",
    ),
    "activity_walking_intro": _l(
        "Marked paths cross the woods and valleys around Ortho, with longer outings beside the Ourthe and the Nisramont reservoir.",
        "Des itinéraires balisés traversent les bois et les vallées autour d’Ortho, avec des sorties plus longues le long de l’Ourthe et du lac de Nisramont.",
        "Gemarkeerde routes lopen door de bossen en valleien rond Ortho, met langere tochten langs de Ourthe en het stuwmeer van Nisramont.",
        "Markierte Wege führen durch die Wälder und Täler rund um Ortho; längere Touren verlaufen an der Ourthe und am Stausee von Nisramont.",
        "Markerade leder går genom skogarna och dalarna runt Ortho, med längre turer längs Ourthe och Nisramontsjön.",
        "Markéiert Weeër féieren duerch d'Bëscher an Däller ronderëm Ortho; méi laang Touren lafen laanscht d'Ourthe an de Séi vun Nisramont.",
    ),
    "activity_cycling_intro": _l(
        "Local providers offer bikes, e-bikes and guided rides for exploring the roads and trails of the Ourthe valley.",
        "Des prestataires locaux proposent vélos, vélos électriques et sorties guidées pour parcourir les routes et sentiers de la vallée de l’Ourthe.",
        "Lokale aanbieders verhuren fietsen en e-bikes en organiseren begeleide tochten over de wegen en paden van de Ourthevallei.",
        "Lokale Anbieter vermieten Fahrräder und E-Bikes und bieten geführte Touren auf den Wegen des Ourthe-Tals an.",
        "Lokala arrangörer hyr ut cyklar och elcyklar och erbjuder guidade turer på vägar och leder i Ourthedalen.",
        "Lokal Ubidder verloune Vëloen an E-Bikes a bidden guidéiert Touren op de Weeër am Ourthe-Dall un.",
    ),
    "activity_water_intro": _l(
        "Kayaking and rafting reveal the Ourthe from another angle. Conditions and opening periods vary, so check with the provider before setting out.",
        "Le kayak et le rafting permettent de découvrir l’Ourthe autrement. Les conditions et périodes d’ouverture varient : vérifiez-les auprès du prestataire avant de partir.",
        "Kajakken en raften laten de Ourthe van een andere kant zien. Omstandigheden en openingsperiodes variëren; controleer die voor vertrek bij de aanbieder.",
        "Beim Kajakfahren und Rafting zeigt sich die Ourthe aus einer anderen Perspektive. Bedingungen und Öffnungszeiten variieren; bitte vorab beim Anbieter prüfen.",
        "Kajak och forsränning visar Ourthe från ett annat perspektiv. Förhållanden och öppettider varierar, så kontrollera med arrangören före avfärd.",
        "Beim Kajak a Rafting entdeckt een d'Ourthe aus enger anerer Perspektiv. D'Konditiounen an d'Ëffnungszäite variéieren; informéiert Iech virum Depart beim Ubidder.",
    ),
    "activity_culture_intro": _l(
        "Celtic remains, a medieval castle and local heritage tell the story of the landscape around La Roche-en-Ardenne.",
        "Vestiges celtiques, château médiéval et patrimoine local racontent l’histoire du paysage autour de La Roche-en-Ardenne.",
        "Keltische overblijfselen, een middeleeuws kasteel en lokaal erfgoed vertellen het verhaal van het landschap rond La Roche-en-Ardenne.",
        "Keltische Spuren, eine mittelalterliche Burg und regionales Kulturerbe erzählen von der Landschaft rund um La Roche-en-Ardenne.",
        "Keltiska lämningar, en medeltida borg och lokalt kulturarv berättar om landskapet runt La Roche-en-Ardenne.",
        "Keltesch Spueren, eng mëttelalterlech Buerg a lokalt Patrimoine erzielen d'Geschicht vun der Landschaft ronderëm La Roche-en-Ardenne.",
    ),
    "activity_family_intro": _l(
        "Animal parks, caves and forest experiences offer straightforward ideas for a day out with children.",
        "Parcs animaliers, grottes et découvertes en forêt offrent des idées simples pour une journée avec les enfants.",
        "Dierenparken, grotten en bosbelevenissen bieden toegankelijke ideeën voor een dag met kinderen.",
        "Tierparks, Höhlen und Walderlebnisse bieten unkomplizierte Ideen für einen Ausflug mit Kindern.",
        "Djurparker, grottor och skogsupplevelser ger enkla förslag för en dag med barn.",
        "Déiereparken, Hielen a Bëscherfarunge bidden einfach Iddie fir en Dag mat Kanner.",
    ),
    "activities_stay_title": _l("Stay close to it all.", "Séjournez au cœur de la région.", "Verblijf midden in de streek.", "Mitten in der Region wohnen.", "Bo mitt i regionen.", "Logéiert am Häerz vun der Regioun."),
    "activities_stay_copy": _l(
        "La Grange and Le Cottage each welcome up to eight guests in Ortho, with the forests and La Roche-en-Ardenne close at hand.",
        "La Grange et Le Cottage accueillent chacune jusqu’à huit personnes à Ortho, à proximité des forêts et de La Roche-en-Ardenne.",
        "La Grange en Le Cottage ontvangen elk maximaal acht gasten in Ortho, vlak bij de bossen en La Roche-en-Ardenne.",
        "La Grange und Le Cottage bieten in Ortho jeweils Platz für bis zu acht Gäste, nahe den Wäldern und La Roche-en-Ardenne.",
        "La Grange och Le Cottage välkomnar upp till åtta gäster vardera i Ortho, nära skogarna och La Roche-en-Ardenne.",
        "La Grange an Le Cottage empfänken zu Ortho jeeweils bis zu aacht Gäscht, no bei de Bëscher a La Roche-en-Ardenne.",
    ),
    "gallery_label": _l("Photo gallery", "Galerie photos", "Fotogalerij", "Fotogalerie", "Fotogalleri", "Fotogalerie"),
    "close_gallery": _l("Close gallery", "Fermer la galerie", "Galerij sluiten", "Galerie schließen", "Stäng galleriet", "Galerie zoumaachen"),
    "previous": _l("Previous photograph", "Photo précédente", "Vorige foto", "Vorheriges Foto", "Föregående foto", "Viregt Bild"),
    "next": _l("Next photograph", "Photo suivante", "Volgende foto", "Nächstes Foto", "Nästa foto", "Nächst Bild"),
    "booking_title": _l("Plan your stay.", "Préparez votre séjour.", "Plan uw verblijf.", "Planen Sie Ihren Aufenthalt.", "Planera din vistelse.", "Plangt Ären Openthalt."),
    "capacity": _l("guests", "personnes", "gasten", "Gäste", "gäster", "Gäscht"),
    "programme_cta": _l("Talk about this programme", "Parler de ce programme", "Bespreek dit programma", "Über dieses Programm sprechen", "Prata om programmet", "Kontaktéiert eis fir méi Informatiounen iwwer eis Programmer"),
    "sales_cta": _l("Talk about your search", "Parler de votre recherche", "Bespreek uw zoektocht", "Über Ihre Suche sprechen", "Berätta vad du söker", "Iwwer Är Sich schwätzen"),
    "programmes_list_title": _l("Choose the right programme", "Choisir le programme adapté", "Kies het passende programma", "Das passende Programm wählen", "Välj rätt program", "De passende Programm wielen"),
    "facilities_detail_title": _l("Facilities for daily work", "Des installations pour le travail quotidien", "Faciliteiten voor het dagelijkse werk", "Anlage für die tägliche Arbeit", "Anläggning för det dagliga arbetet", "Infrastrukture fir déi deeglech Aarbecht"),
    "gallery_title": _l("Inside and outside", "À l’intérieur et à l’extérieur", "Binnen en buiten", "Innen und außen", "Inomhus och utomhus", "Bannen a baussen"),
    "instagram_fallback": _l("View the latest posts on Instagram", "Voir les dernières publications sur Instagram", "Bekijk de nieuwste berichten op Instagram", "Neueste Beiträge auf Instagram ansehen", "Se de senaste inläggen på Instagram", "Déi lescht Bäiträg op Instagram kucken"),
    "read_story": _l("Read the story", "Lire son histoire", "Lees het verhaal", "Geschichte lesen", "Läs berättelsen", "Geschicht liesen"),
    "dalton_gallery": _l("Dalton at Falsterbo", "Dalton à Falsterbo", "Dalton in Falsterbo", "Dalton in Falsterbo", "Dalton i Falsterbo", "Den Dalton zu Falsterbo"),
}


def ui(key, lang):
    """Return a required short UI label."""
    return UI[key][lang]


MEDIA = {
    "home_hero": "hero-horses-2000.webp",
    "intro": "horse-4.jpg",
    "boarding": "prepinson-stables-flowers.webp",
    "training": "training-2000.webp",
    "breeding": "prepinson-mare-and-foal.webp",
    "facilities": "facilities-2000.webp",
    "team_eva": "eva-schiller.jpg",
    "team_nicolas": "nicolas-derouault.jpg",
    "houses": "house-hero-2000.webp",
    "ortho24": "grange-1.jpg",
    "ortho25": "cottage.jpg",
}


PROPERTIES = {
    "ortho-24": {
        "short": "Ortho 24, La Grange",
        "image": "grange-1.jpg",
        "booking": "https://www.casapilot.com/en/1091854-holiday-home-in-la-roche-en-ardenne-ardennes-and-eifel-belgium",
        "platform": "Casapilot",
        "bedrooms": 4,
        "bathrooms": 4,
        "gallery": tuple((f"grange-{i}.jpg", f"Ortho 24, La Grange, photograph {i}") for i in range(1, 7)),
    },
    "ortho-25": {
        "short": "Ortho 25, Le Cottage",
        "image": "cottage.jpg",
        "booking": "https://airbnb.com/h/ortho25",
        "platform": "Airbnb",
        "bedrooms": 3,
        "bathrooms": 3,
        "gallery": (("cottage.jpg", "Ortho 25, Le Cottage, stone exterior"),) + tuple((f"cottage-{i}.jpg", f"Ortho 25, Le Cottage, photograph {i}") for i in range(1, 6)),
    },
}


ACTIVITIES = (
    ("act_walk", (
        ("Ortho-Hives Tourisme", "https://www.ortho-hives-tourisme.com/randonner"),
        ("Lac et barrage de Nisramont", "https://www.la-roche-tourisme.com/le-lac-et-le-barrage-de-nisramont/"),
        ("Le Hérou", "https://www.luxembourg-belge.be/diffusio/fr/voir-faire/visiter/patrimoine-naturel/nadrin/le-herou_TFOALD-01-08H9-01.php"),
        ("Le Cheslé", "https://www.la-roche-tourisme.com/la-forteresse-celtique-du-chesle/"),
    )),
    ("act_cycle", (
        ("SoWatt e-bike", "https://sowatt.bike/fr"),
        ("Wildtrails", "https://www.wildtrails.be/"),
        ("Brandsport", "https://www.brandsport.be/"),
        ("Ardenne Aventures", "https://ardenneaventures.com/"),
        ("Trott-e-Trail", "https://www.trott-e-trail.com/"),
    )),
    ("act_family", (
        ("La Roche-en-Ardenne Tourisme", "https://www.la-roche-tourisme.com/"),
        ("Château féodal de La Roche-en-Ardenne", "https://www.chateaudelaroche.be/"),
        ("Parc à Gibier", "https://www.parc-gibier-laroche.be/"),
        ("Grottes de Hotton", "https://grottesdehotton.be/"),
        ("Parc Chlorophylle", "https://www.parcchlorophylle.com/"),
        ("Houtopia", "https://www.houtopia.be/"),
        ("Brasserie d'Achouffe", "https://chouffe.com/"),
    )),
)


# Approved V1 presentation, extracted from fd597a0; line breaks and italics are intentional.
V1_COPY = {'en': {'home_hero': 'A life dedicated<br>to <em>horses.</em>',
        'home_eyebrow': 'HARAS DE PREPINSON · BELGIUM',
        'home_tagline': 'Breeding, young horse training and boarding<br>in the Belgian Ardennes.',
        'home_intro_title': 'Horses first.<br><em>Always.</em>',
        'home_intro': 'We breed and train young horses in Ortho, in the Belgian Ardennes. Our programmes cover foal handling, preparation '
                      'for backing, early ridden work and show jumping.',
        'home_intro_secondary': 'Boarding and daily care take place in quiet surroundings, with work in the arenas and in the forest.',
        'home_intro_link': 'Discover our activities',
        'expertise_title': 'Our work<br><em>with horses.</em>',
        'expertise_intro': 'Boarding, training and breeding, adapted to each horse.',
        'team_title': 'Experience, instinct<br><em>and daily care.</em>',
        'team_intro': 'Prepinson is shaped by a small, committed team and a shared belief: every horse deserves individual attention, '
                      'patience and the right environment.',
        'home_services_line': 'BREEDING &nbsp; / &nbsp; TRAINING &nbsp; / &nbsp; CARE',
        'hero_film': 'A moment at Prepinson<br><small>WATCH THE FILM</small>',
        'journal_title': 'Daily life<br><em>at Prepinson.</em>',
        'journal_intro': 'A closer look at our work, through stories shared on Instagram.',
        'horses_hero': 'Horses at Prepinson.<br><em>Our daily work.</em>',
        'horses_tagline': 'Attentive care and patient training, adapted to each horse.',
        'houses_hero': 'Make room<br><em>for slow living.</em>',
        'houses_tagline': 'Two holiday homes in the heart of the Ardennes.',
        'houses_intro_title': 'Come together.<br><em>Feel at home.</em>',
        'houses_instagram_title': 'Life at our<br><em>holiday homes.</em>',
        'houses_instagram_copy': 'Seasonal details, new views and everyday moments from Ortho 24 and Ortho 25.',
        'houses_estate_title': 'Less rush.<br><em>More Ardennes.</em>',
        'houses_estate_copy': 'Walk through the forests, explore La Roche-en-Ardenne or simply find a quiet spot in the garden. The best '
                              'days here leave a little room for nothing at all.',
        'house_detail_intro': 'A house<br><em>in the Ardennes.</em>',
        'ortho24_copy': 'A generous Ardennes retreat, where stone walls meet contemporary comfort. Gather with family or friends, settle '
                        'into slow mornings and make the most of the pool and outdoor hot tub.',
        'ortho24_amenities': '<span>8 guests</span><span>4 bedrooms</span><span>4 bathrooms</span><span>Outdoor pool</span><span>Hot '
                             'tub</span><span>Home cinema</span>',
        'ortho25_copy': 'A welcoming stone cottage in the village of Ortho. With a private garden and space for eight, it is a lovely base '
                        'for forest walks, unhurried lunches and time together in the Ardennes.',
        'ortho25_amenities': '<span>8 guests</span><span>3 bedrooms</span><span>3 bathrooms</span><span>Private '
                             'garden</span><span>Kitchen</span><span>2 parking spaces</span>'},
 'fr': {'home_hero': 'Une vie consacrée<br>aux <em>chevaux.</em>',
        'home_eyebrow': 'HARAS DE PREPINSON · BELGIQUE',
        'home_tagline': 'Élevage, formation des jeunes chevaux et pension<br>dans les Ardennes belges.',
        'home_intro_title': 'Les chevaux d’abord.<br><em>Toujours.</em>',
        'home_intro': 'À Ortho, dans les Ardennes belges, Prepinson réunit élevage, pension et formation de jeunes chevaux. Nos programmes '
                      'accompagnent leurs premiers apprentissages, le débourrage et la préparation au saut d’obstacles.',
        'home_intro_secondary': 'Le travail se déroule dans les pistes et en forêt, dans le respect du rythme de chaque cheval.',
        'home_intro_link': 'Découvrir nos activités',
        'expertise_title': 'Notre travail<br><em>avec les chevaux.</em>',
        'expertise_intro': 'Pension, formation et élevage, adaptés à chaque cheval.',
        'team_title': 'Expérience, instinct<br><em>et attention quotidienne.</em>',
        'team_intro': 'Prepinson est porté par une petite équipe engagée et une conviction commune : chaque cheval mérite une attention '
                      'individuelle, de la patience et un environnement adapté.',
        'home_services_line': 'ÉLEVAGE / FORMATION / SOINS',
        'hero_film': 'Un instant à Prepinson<br><small>VOIR LE FILM</small>',
        'journal_title': 'Le quotidien<br><em>à Prepinson.</em>',
        'journal_intro': 'Un regard sur notre travail, à travers les histoires partagées sur Instagram.',
        'horses_hero': 'Les chevaux à Prepinson.<br><em>Les premiers apprentissages.</em>',
        'horses_tagline': 'Des soins attentifs et une formation adaptée au rythme de chaque cheval.',
        'houses_hero': 'Prenez le temps<br><em>de ralentir.</em>',
        'houses_tagline': 'Deux maisons de vacances au cœur des Ardennes.',
        'houses_intro_title': 'Se retrouver.<br><em>Se sentir chez soi.</em>',
        'houses_instagram_title': 'Les maisons,<br><em>au fil des séjours.</em>',
        'houses_instagram_copy': 'Détails de saison, nouvelles perspectives et instants du quotidien à Ortho 24 et Ortho 25.',
        'houses_estate_title': 'Moins de hâte.<br><em>Plus d’Ardennes.</em>',
        'houses_estate_copy': 'Promenez-vous en forêt, découvrez La Roche-en-Ardenne ou installez-vous simplement dans le jardin. Ici, les '
                              'plus belles journées laissent une place à l’imprévu.',
        'house_detail_intro': 'Séjourner<br><em>dans les Ardennes.</em>',
        'ortho24_copy': 'Un refuge spacieux dans les Ardennes, entre pierre et confort contemporain. Retrouvez-vous en famille ou entre '
                        'amis, profitez de matinées paisibles, de la piscine et du bain à remous extérieur.',
        'ortho24_amenities': '<span>8 personnes</span><span>4 chambres</span><span>4 salles de bains</span><span>Piscine '
                             'extérieure</span><span>Bain à remous</span><span>Home cinéma</span>',
        'ortho25_copy': 'Un cottage en pierre accueillant au cœur du village d’Ortho. Avec son jardin privé et sa capacité de huit '
                        'personnes, c’est le point de départ idéal pour des balades en forêt et des moments partagés dans les Ardennes.',
        'ortho25_amenities': '<span>8 personnes</span><span>3 chambres</span><span>3 salles de bains</span><span>Jardin '
                             'privé</span><span>Cuisine</span><span>2 places de parking</span>'},
 'nl': {'home_hero': 'Een leven<br>voor <em>paarden.</em>',
        'home_eyebrow': 'HARAS DE PREPINSON · BELGIË',
        'home_tagline': 'Fokkerij, opleiding van jonge paarden en pension<br>in de Belgische Ardennen.',
        'home_intro_title': 'Paarden eerst.<br><em>Altijd.</em>',
        'home_intro': 'In Ortho, in de Belgische Ardennen, fokken en trainen we jonge paarden. Onze programma’s omvatten veulenbegeleiding, '
                      'voorbereiding op het zadelmak maken, de eerste oefeningen onder het zadel en springtraining.',
        'home_intro_secondary': 'Pension en dagelijkse verzorging vinden plaats in een rustige omgeving, met werk in de pistes en in het bos.',
        'home_intro_link': 'Ontdek onze activiteiten',
        'expertise_title': 'Ons werk<br><em>met paarden.</em>',
        'expertise_intro': 'Pension, training en fokkerij, afgestemd op elk paard.',
        'team_title': 'Ervaring, instinct<br><em>en dagelijkse zorg.</em>',
        'team_intro': 'Prepinson wordt gevormd door een klein, betrokken team en één gedeelde overtuiging: elk paard verdient persoonlijke '
                      'aandacht, geduld en de juiste omgeving.',
        'home_services_line': 'FOKKERIJ / OPLEIDING / ZORG',
        'hero_film': 'Een moment op Prepinson<br><small>BEKIJK DE FILM</small>',
        'journal_title': 'Het dagelijks leven<br><em>op Prepinson.</em>',
        'journal_intro': 'Een blik op ons werk, via verhalen die we op Instagram delen.',
        'horses_hero': 'Bijzondere paarden.<br><em>Een doordachte start.</em>',
        'horses_tagline': 'Aandachtige verzorging en opleiding op het tempo van elk paard.',
        'houses_hero': 'Maak ruimte<br><em>voor rust.</em>',
        'houses_tagline': 'Twee vakantiehuizen in het hart van de Ardennen.',
        'houses_intro_title': 'Samenkomen.<br><em>Voel u thuis.</em>',
        'houses_instagram_title': 'Onze vakantiehuizen<br><em>op Instagram.</em>',
        'houses_instagram_copy': 'Seizoensdetails, nieuwe perspectieven en alledaagse momenten uit Ortho 24 en Ortho 25.',
        'houses_estate_title': 'Minder haast.<br><em>Meer Ardennen.</em>',
        'houses_estate_copy': 'Wandel door de bossen, ontdek La Roche-en-Ardenne of zoek een rustig plekje in de tuin. De mooiste dagen '
                              'laten ruimte om even niets te doen.',
        'house_detail_intro': 'Verblijven<br><em>in de Ardennen.</em>',
        'ortho24_copy': 'Een ruim toevluchtsoord in de Ardennen, waar natuursteen en modern comfort samenkomen. Geniet met familie of '
                        'vrienden van rustige ochtenden, het zwembad en de buitenjacuzzi.',
        'ortho24_amenities': '<span>8 personen</span><span>4 slaapkamers</span><span>4 '
                             'badkamers</span><span>Buitenzwembad</span><span>Jacuzzi</span><span>Thuisbioscoop</span>',
        'ortho25_copy': 'Een gastvrije stenen cottage in het dorp Ortho. Met een privétuin en plaats voor acht personen is het een fijne '
                        'uitvalsbasis voor boswandelingen en samenzijn in de Ardennen.',
        'ortho25_amenities': '<span>8 personen</span><span>3 slaapkamers</span><span>3 '
                             'badkamers</span><span>Privétuin</span><span>Keuken</span><span>2 parkeerplaatsen</span>'},
 'de': {'home_hero': 'Ein Leben<br>für <em>Pferde.</em>',
        'home_eyebrow': 'HARAS DE PREPINSON · BELGIEN',
        'home_tagline': 'Zucht, Jungpferdeausbildung und Pension<br>in den belgischen Ardennen.',
        'home_intro_title': 'Pferde zuerst.<br><em>Immer.</em>',
        'home_intro': 'In Ortho in den belgischen Ardennen züchten und arbeiten wir mit jungen Pferden. Unsere Programme umfassen '
                      'Fohlenhandling, die Vorbereitung auf das Anreiten, die erste Arbeit unter dem Sattel und Springtraining.',
        'home_intro_secondary': 'Pension und tägliche Betreuung finden in ruhiger Umgebung statt; gearbeitet wird auf den Plätzen und im Wald.',
        'home_intro_link': 'Unsere Angebote entdecken',
        'expertise_title': 'Junge Pferde<br><em>ausbilden.</em>',
        'expertise_intro': 'Pension, Ausbildung und Zucht, abgestimmt auf jedes Pferd.',
        'team_title': 'Erfahrung, Gespür<br><em>und tägliche Fürsorge.</em>',
        'team_intro': 'Prepinson wird von einem kleinen, engagierten Team und einer gemeinsamen Überzeugung geprägt: Jedes Pferd verdient '
                      'individuelle Aufmerksamkeit, Geduld und das richtige Umfeld.',
        'home_services_line': 'ZUCHT / AUSBILDUNG / FÜRSORGE',
        'hero_film': 'Ein Moment in Prepinson<br><small>FILM ANSEHEN</small>',
        'journal_title': 'Der Alltag<br><em>in Prepinson.</em>',
        'journal_intro': 'Ein Einblick in unsere Arbeit durch Geschichten auf Instagram.',
        'horses_hero': 'Besondere Pferde.<br><em>Ein durchdachter Anfang.</em>',
        'horses_tagline': 'Aufmerksame Betreuung und Ausbildung im Tempo jedes Pferdes.',
        'houses_hero': 'Zeit nehmen<br><em>für die Ruhe.</em>',
        'houses_tagline': 'Zwei Ferienhäuser im Herzen der Ardennen.',
        'houses_intro_title': 'Zusammenkommen.<br><em>Sich zu Hause fühlen.</em>',
        'houses_instagram_title': 'Einblicke in unsere<br><em>Ferienhäuser.</em>',
        'houses_instagram_copy': 'Saisonale Details, neue Perspektiven und Alltagsmomente aus Ortho 24 und Ortho 25.',
        'houses_estate_title': 'Weniger Eile.<br><em>Mehr Ardennen.</em>',
        'houses_estate_copy': 'Spazieren Sie durch die Wälder, entdecken Sie La Roche-en-Ardenne oder suchen Sie sich einen ruhigen Platz '
                              'im Garten. Die schönsten Tage lassen Raum fürs Nichtstun.',
        'house_detail_intro': 'Urlaub<br><em>in den Ardennen.</em>',
        'ortho24_copy': 'Ein großzügiger Rückzugsort in den Ardennen, der Steinmauern mit modernem Komfort verbindet. Genießen Sie mit '
                        'Familie oder Freunden ruhige Morgen, den Pool und den Whirlpool im Freien.',
        'ortho24_amenities': '<span>8 Gäste</span><span>4 Schlafzimmer</span><span>4 '
                             'Badezimmer</span><span>Außenpool</span><span>Whirlpool</span><span>Heimkino</span>',
        'ortho25_copy': 'Ein einladendes Steinhaus im Dorf Ortho. Mit privatem Garten und Platz für acht Gäste ist es ein schöner '
                        'Ausgangspunkt für Waldspaziergänge und gemeinsame Zeit in den Ardennen.',
        'ortho25_amenities': '<span>8 Gäste</span><span>3 Schlafzimmer</span><span>3 Badezimmer</span><span>Privater '
                             'Garten</span><span>Küche</span><span>2 Parkplätze</span>'},
 'sv': {'home_hero': 'Ett liv<br>med <em>hästar.</em>',
        'home_eyebrow': 'HARAS DE PREPINSON · BELGIEN',
        'home_tagline': 'Avel, unghästutbildning och uppstallning<br>i belgiska Ardennerna.',
        'home_intro_title': 'Hästarna först.<br><em>Alltid.</em>',
        'home_intro': 'I Ortho i belgiska Ardennerna föder vi upp och utbildar unghästar. Våra program omfattar fölhantering, förberedelse '
                      'för inridning, den första ridningen och hoppträning.',
        'home_intro_secondary': 'Uppstallning och daglig omsorg sker i lugna omgivningar, med arbete på banorna och i skogen.',
        'home_intro_link': 'Upptäck vår verksamhet',
        'expertise_title': 'Vårt arbete<br><em>med hästarna.</em>',
        'expertise_intro': 'Uppstallning, utbildning och avel, anpassad till varje häst.',
        'team_title': 'Erfarenhet, känsla<br><em>och daglig omsorg.</em>',
        'team_intro': 'Prepinson formas av ett litet, engagerat team och en gemensam övertygelse: varje häst förtjänar individuell '
                      'uppmärksamhet, tålamod och rätt miljö.',
        'home_services_line': 'AVEL / UTBILDNING / OMSORG',
        'hero_film': 'Ett ögonblick på Prepinson<br><small>SE FILMEN</small>',
        'journal_title': 'Vardagen<br><em>på Prepinson.</em>',
        'journal_intro': 'En närmare titt på vårt arbete genom berättelser på Instagram.',
        'horses_hero': 'Exceptionella hästar.<br><em>En genomtänkt början.</em>',
        'horses_tagline': 'Omsorg och utbildning i varje hästs egen takt.',
        'houses_hero': 'Gör plats<br><em>för lugnet.</em>',
        'houses_tagline': 'Två semesterhus i hjärtat av Ardennerna.',
        'houses_intro_title': 'Samlas.<br><em>Känn dig hemma.</em>',
        'houses_instagram_title': 'Bilder från våra<br><em>semesterhus.</em>',
        'houses_instagram_copy': 'Säsongens detaljer, nya vyer och vardagsögonblick från Ortho 24 och Ortho 25.',
        'houses_estate_title': 'Mindre brådska.<br><em>Mer Ardennerna.</em>',
        'houses_estate_copy': 'Promenera i skogen, upptäck La Roche-en-Ardenne eller hitta en lugn plats i trädgården. De bästa dagarna '
                              'lämnar utrymme för att bara vara.',
        'house_detail_intro': 'Boende<br><em>i Ardennerna.</em>',
        'ortho24_copy': 'En rymlig tillflyktsort i Ardennerna där stenväggar möter modern komfort. Samla familj eller vänner och njut av '
                        'lugna morgnar, poolen och bubbelpoolen utomhus.',
        'ortho24_amenities': '<span>8 gäster</span><span>4 sovrum</span><span>4 '
                             'badrum</span><span>Utomhuspool</span><span>Bubbelpool</span><span>Hemmabio</span>',
        'ortho25_copy': 'Ett välkomnande stenhus i byn Ortho. Med en privat trädgård och plats för åtta är det en fin utgångspunkt för '
                        'skogspromenader och tid tillsammans i Ardennerna.',
        'ortho25_amenities': '<span>8 gäster</span><span>3 sovrum</span><span>3 badrum</span><span>Privat '
                             'trädgård</span><span>Kök</span><span>2 parkeringsplatser</span>'},
 'lb': {'home_hero': 'E Liewe<br>fir <em>d’Päerd.</em>',
        'home_eyebrow': 'HARAS DE PREPINSON · BELSCH',
        'home_tagline': 'Zuucht, Ausbildung vu jonke Päerd a Pensioun<br>an de belschen Ardennen.',
        'home_intro_title': 'D’Päerd fir d’éischt.<br><em>Ëmmer.</em>',
        'home_intro': "Zu Ortho an de belschen Ardenne ziichten an trainéiere mir jonk Päerd. Eis Programmer ëmfaassen den Ëmgang mam "
                      "Fëllen, d’Virbereedung op d’Ureiden, déi éischt Aarbecht ënner dem Suedel an d'Sprangtraining.",
        'home_intro_secondary': 'D’Pensioun an déi deeglech Betreiung fanne roueg statt, mat Aarbecht op de Pisten an am Bësch.',
        'home_intro_link': 'Eis Aktivitéiten entdecken',
        'expertise_title': 'Eis Aarbecht<br><em>mat de Päerd.</em>',
        'expertise_intro': 'Pensioun, Ausbildung an Zuucht, un all Päerd ugepasst.',
        'team_title': 'Erfarung, Instinkt<br><em>an deeglech Betreiung.</em>',
        'team_intro': 'Prepinson gëtt vun engem klengen, engagéierten Team an enger gemeinsamer Iwwerzeegung gepräägt: All Päerd verdéngt '
                      'individuell Opmierksamkeet, Gedold an dat richtegt Ëmfeld.',
        'home_services_line': 'ZUUCHT / AUSBILDUNG / BETREIUNG',
        'hero_film': 'E Moment zu Prepinson<br><small>DE FILM KUCKEN</small>',
        'journal_title': 'Den Alldag<br><em>zu Prepinson.</em>',
        'journal_intro': 'En Abléck an eis Aarbecht duerch Geschichten, déi mir op Instagram deelen.',
        'horses_hero': 'Aussergewéinlech Päerd.<br><em>Duerchduechten Ufäng.</em>',
        'horses_tagline': 'Opmierksam Betreiung an Ausbildung am Rhythmus vun all Päerd.',
        'houses_hero': 'Huelt Iech Zäit<br><em>fir Rou.</em>',
        'houses_tagline': 'Zwee Vakanzenhaiser am Häerz vun den Ardennen.',
        'houses_intro_title': 'Zesummekommen.<br><em>Sech doheem fillen.</em>',
        'houses_instagram_title': 'D’Haiser,<br><em>wéi se gelieft ginn.</em>',
        'houses_instagram_copy': 'Saisonal Detailer, nei Perspektiven an Alldagsmomenter aus Ortho 24 an Ortho 25.',
        'houses_estate_title': 'Manner Hetz.<br><em>Méi Ardennen.</em>',
        'houses_estate_copy': 'Spadséiert duerch d’Bëscher, entdeckt La Roche-en-Ardenne oder sicht Iech eng roueg Plaz am Gaart. Déi '
                              'schéinst Deeg loossen Zäit fir einfach näischt ze maachen.',
        'house_detail_intro': 'Vakanz<br><em>an den Ardennen.</em>',
        'ortho24_copy': 'E grousszügege Réckzuchsuert an den Ardennen, wou Steemaueren op moderne Komfort treffen. Genéisst mat der Famill '
                        'oder Frënn roueg Moien, d’Schwämm an de Whirlpool dobaussen.',
        'ortho24_amenities': '<span>8 Persounen</span><span>4 Schlofkummeren</span><span>4 Buedzëmmeren</span><span>Schwämm '
                             'dobaussen</span><span>Whirlpool</span><span>Heemkino</span>',
        'ortho25_copy': 'E gemittlecht Steehaus am Duerf Ortho. Mat engem private Gaart a Plaz fir aacht Leit ass et e flotte Startpunkt '
                        'fir Bëschspadséiergäng a gemeinsam Zäit an den Ardennen.',
        'ortho25_amenities': '<span>8 Persounen</span><span>3 Schlofkummeren</span><span>3 Buedzëmmeren</span><span>Private '
                             'Gaart</span><span>Kichen</span><span>2 Parkplazen</span>'}}

def v1(key, lang):
    return V1_COPY[lang][key]


UI.update({'ortho24_tag': {'en': 'Space to gather. Room to unwind.',
                 'fr': 'L’espace de se retrouver. Le temps de souffler.',
                 'nl': 'Ruimte om samen te komen. Tijd om te ontspannen.',
                 'de': 'Platz für Gemeinsamkeit. Raum zum Entspannen.',
                 'sv': 'Plats att samlas. Utrymme att koppla av.',
                 'lb': 'Plaz fir zesummenzekommen. Zäit fir auszespannen.'},
 'ortho25_tag': {'en': 'Country character. A cosy escape.',
                 'fr': 'Le charme de la campagne. Un cocon chaleureux.',
                 'nl': 'Landelijke charme. Een gezellig verblijf.',
                 'de': 'Ländlicher Charme. Eine gemütliche Auszeit.',
                 'sv': 'Lantlig charm. En ombonad tillflyktsort.',
                 'lb': 'Ländleche Charme. Eng gemittlech Auszäit.'},
 'pool': {'en': 'Outdoor pool',
          'fr': 'Piscine extérieure',
          'nl': 'Buitenzwembad',
          'de': 'Außenpool',
          'sv': 'Utomhuspool',
          'lb': 'Schwämm dobaussen'},
 'hot_tub': {'en': 'Hot tub',
             'fr': 'Bain à remous',
             'nl': 'Jacuzzi',
             'de': 'Whirlpool',
             'sv': 'Bubbelpool',
             'lb': 'Whirlpool'},
 'cinema': {'en': 'Home cinema',
            'fr': 'Home cinéma',
            'nl': 'Thuisbioscoop',
            'de': 'Heimkino',
            'sv': 'Hemmabio',
            'lb': 'Heemkino'},
 'garden': {'en': 'Private garden',
            'fr': 'Jardin privé',
            'nl': 'Privétuin',
            'de': 'Privater Garten',
            'sv': 'Privat trädgård',
            'lb': 'Private Gaart'},
 'kitchen': {'en': 'Kitchen', 'fr': 'Cuisine', 'nl': 'Keuken', 'de': 'Küche', 'sv': 'Kök', 'lb': 'Kichen'},
 'parking': {'en': '2 parking spaces',
             'fr': '2 places de parking',
             'nl': '2 parkeerplaatsen',
             'de': '2 Parkplätze',
             'sv': '2 parkeringsplatser',
             'lb': '2 Parkplazen'},
 'country': {'en': 'Belgium', 'fr': 'Belgique', 'nl': 'België', 'de': 'Belgien', 'sv': 'Belgien', 'lb': 'Belsch'},
 'enlarge': {'en': 'Enlarge photograph',
             'fr': 'Agrandir la photographie',
             'nl': 'Foto vergroten',
             'de': 'Foto vergrößern',
             'sv': 'Förstora fotografiet',
             'lb': 'Foto vergréisseren'}})

GALLERY_ALT = {'grange-1.jpg': {'en': 'La Grange and its outdoor pool',
                  'fr': 'La Grange et sa piscine extérieure',
                  'nl': 'La Grange en het buitenzwembad',
                  'de': 'La Grange mit Außenpool',
                  'sv': 'La Grange och utomhuspoolen',
                  'lb': 'La Grange mat Baussepool'},
 'grange-2.jpg': {'en': 'Pool terrace and stone façade',
                  'fr': 'Terrasse de la piscine et façade en pierre',
                  'nl': 'Zwembadterras en stenen gevel',
                  'de': 'Poolterrasse und Steinfassade',
                  'sv': 'Poolterrass och stenfasad',
                  'lb': 'Poolterrass a Steefassad'},
 'grange-3.jpg': {'en': 'La Grange, garden and pool seen from above',
                  'fr': 'La Grange, le jardin et la piscine vus du ciel',
                  'nl': 'La Grange, tuin en zwembad vanuit de lucht',
                  'de': 'La Grange, Garten und Pool aus der Luft',
                  'sv': 'La Grange, trädgård och pool från ovan',
                  'lb': 'La Grange, Gaart a Pool vun uewen'},
 'grange-4.jpg': {'en': 'La Grange and the neighbouring equestrian facilities',
                  'fr': 'La Grange et les installations équestres voisines',
                  'nl': 'La Grange en de aangrenzende paardenfaciliteiten',
                  'de': 'La Grange und die benachbarte Reitanlage',
                  'sv': 'La Grange och den närliggande ridanläggningen',
                  'lb': 'La Grange an déi niewendrun Infrastrukture fir Päerd'},
 'grange-5.jpg': {'en': 'Sun loungers beside the pool overlooking the fields',
                  'fr': 'Transats au bord de la piscine, face aux prairies',
                  'nl': 'Ligstoelen bij het zwembad met uitzicht op de velden',
                  'de': 'Liegestühle am Pool mit Blick auf die Wiesen',
                  'sv': 'Solstolar vid poolen med utsikt över fälten',
                  'lb': 'Loungestill beim Pool mat Vue op d’Wisen'},
 'grange-6.jpg': {'en': 'Outdoor pool and terrace facing the countryside',
                  'fr': 'Piscine extérieure et terrasse face à la campagne',
                  'nl': 'Buitenzwembad en terras met uitzicht op het platteland',
                  'de': 'Außenpool und Terrasse mit Blick aufs Land',
                  'sv': 'Utomhuspool och terrass mot landsbygden',
                  'lb': 'Baussepool an Terrass mat Vue op d’Landschaft'},
 'cottage.jpg': {'en': 'Stone exterior of Le Cottage in Ortho',
                 'fr': 'Façade en pierre du Cottage à Ortho',
                 'nl': 'Stenen buitengevel van Le Cottage in Ortho',
                 'de': 'Steinfassade des Cottage in Ortho',
                 'sv': 'Stenfasaden på Le Cottage i Ortho',
                 'lb': 'Steefassad vum Cottage zu Ortho'},
 'cottage-1.jpg': {'en': 'Le Cottage living room with red sofa',
                   'fr': 'Salon du Cottage avec canapé rouge',
                   'nl': 'Woonkamer van Le Cottage met rode bank',
                   'de': 'Wohnzimmer des Cottage mit rotem Sofa',
                   'sv': 'Vardagsrum med röd soffa i Le Cottage',
                   'lb': 'Stuff vum Cottage mat rouder Couche'},
 'cottage-2.jpg': {'en': 'Le Cottage dining room and fireplace',
                   'fr': 'Salle à manger et cheminée du Cottage',
                   'nl': 'Eetkamer en open haard van Le Cottage',
                   'de': 'Esszimmer und Kamin im Cottage',
                   'sv': 'Matrum och öppen spis i Le Cottage',
                   'lb': 'Iesszëmmer a Kamäin am Cottage'},
 'cottage-3.jpg': {'en': 'Le Cottage bedroom',
                   'fr': 'Chambre du Cottage',
                   'nl': 'Slaapkamer van Le Cottage',
                   'de': 'Schlafzimmer im Cottage',
                   'sv': 'Sovrum i Le Cottage',
                   'lb': 'Schlofzëmmer am Cottage'},
 'cottage-4.jpg': {'en': 'Le Cottage sitting and dining area',
                   'fr': 'Salon et espace repas du Cottage',
                   'nl': 'Zit- en eetruimte van Le Cottage',
                   'de': 'Wohn- und Essbereich im Cottage',
                   'sv': 'Vardagsrum och matplats i Le Cottage',
                   'lb': 'Wunn- an Iessberäich am Cottage'},
 'cottage-5.jpg': {'en': 'Entrance hall and wooden staircase in Le Cottage',
                   'fr': 'Entrée et escalier en bois du Cottage',
                   'nl': 'Entree en houten trap van Le Cottage',
                   'de': 'Eingang und Holztreppe im Cottage',
                   'sv': 'Entré och trätrappa i Le Cottage',
                   'lb': 'Agank an hëlzent Trap am Cottage'}}

UI.update({'boarding_copy': {'en': 'Individual attention, daily supervision and room to thrive. A home for every stage of life.',
                   'fr': 'Une attention individuelle, une surveillance quotidienne et de l’espace pour s’épanouir. Un lieu '
                         'adapté à chaque étape de la vie.',
                   'nl': 'Persoonlijke aandacht, dagelijks toezicht en ruimte om te groeien. Een thuis voor elke levensfase.',
                   'de': 'Individuelle Aufmerksamkeit, tägliche Betreuung und Raum zur Entfaltung. Ein Zuhause für jede '
                         'Lebensphase.',
                   'sv': 'Individuell omsorg, daglig tillsyn och utrymme att trivas. Ett hem för varje skede i livet.',
                   'lb': 'Individuell Opmierksamkeet, deeglech Kontroll a Plaz fir sech z’entwéckelen. En Doheem fir all '
                         'Liewensphas.'},
 'training_copy': {'en': 'Patient, professional young horse training. Strong foundations for a future in sport.',
                   'fr': 'Une formation patiente et professionnelle des jeunes chevaux. Des bases solides pour leur avenir '
                         'sportif.',
                   'nl': 'Geduldige, professionele opleiding van jonge paarden. Een stevige basis voor een toekomst in de sport.',
                   'de': 'Geduldige, professionelle Jungpferdeausbildung. Ein solides Fundament für die sportliche Zukunft.',
                   'sv': 'Tålmodig och professionell unghästutbildning. En stabil grund för framtiden inom sporten.',
                   'lb': 'Gedëlleg a professionell Ausbildung vu jonke Päerd. Eng zolidd Basis fir hir sportlech Zukunft.'},
 'breeding_copy': {'en': 'Thoughtful beginnings. Bringing together promising bloodlines and attentive horsemanship.',
                   'fr': 'Des débuts réfléchis. Des lignées prometteuses accompagnées d’un travail attentif au quotidien.',
                   'nl': 'Een doordachte start. Veelbelovende bloedlijnen en aandachtige dagelijkse begeleiding.',
                   'de': 'Durchdachte Anfänge. Vielversprechende Blutlinien und aufmerksame tägliche Arbeit.',
                   'sv': 'En genomtänkt start. Lovande blodslinjer och omsorgsfullt dagligt arbete.',
                   'lb': 'Duerchduechten Ufäng. Villverspriechend Bluttlinnen an opmierksam deeglech Aarbecht.'},
 'boarding_title': {'en': 'Boarding & care',
                    'fr': 'Pension & soins',
                    'nl': 'Pension & verzorging',
                    'de': 'Pension & Betreuung',
                    'sv': 'Inackordering & omsorg',
                    'lb': 'Pensioun & Betreiung'},
 'training_title': {'en': 'Training & development',
                    'fr': 'Formation & valorisation',
                    'nl': 'Training & ontwikkeling',
                    'de': 'Ausbildung & Entwicklung',
                    'sv': 'Utbildning & utveckling',
                    'lb': 'Ausbildung & Entwécklung'},
 'horses_intro_first': {'en': 'Every horse.',
                        'fr': 'Un accompagnement',
                        'nl': 'Een aanpak',
                        'de': 'Für jedes Pferd.',
                        'sv': 'Individuell träning',
                        'lb': 'Eng individuell Approche'},
 'horses_intro_second': {'en': 'Every possibility.',
                         'fr': 'adapté à chaque cheval.',
                         'nl': 'op maat van elk paard.',
                         'de': 'Der passende Weg.',
                         'sv': 'för varje häst.',
                         'lb': 'fir all Päerd.'},
 'alt_hero': {'en': 'Mares and foals grazing in the Prepinson pastures',
              'fr': 'Juments et poulains dans les prairies de Prepinson',
              'nl': 'Merries en veulens in de weiden van Prepinson',
              'de': 'Stuten und Fohlen auf den Weiden von Prepinson',
              'sv': 'Ston och föl på Prepinsons betesmarker',
              'lb': 'Stuten a Fëlle bei Prepinson op der Wiss'},
 'alt_intro': {'en': 'A horse and its handler at Prepinson',
               'fr': 'Un cheval et la personne qui en prend soin à Prepinson',
               'nl': 'Een paard en zijn verzorger bij Prepinson',
               'de': 'Ein Pferd und seine Betreuungsperson in Prepinson',
               'sv': 'En häst och dess skötare på Prepinson',
               'lb': 'E Päerd a seng Betreiungspersoun zu Prepinson'},
 'alt_boarding': {'en': 'Horses at the windows of flower-lined stables',
                  'fr': 'Chevaux aux fenêtres des écuries fleuries',
                  'nl': 'Paarden aan de ramen van de stallen met bloemen',
                  'de': 'Pferde an den Fenstern der blumengeschmückten Ställe',
                  'sv': 'Hästar vid fönstren i de blomsterprydda stallen',
                  'lb': 'Päerd un de Fënstere vun de Ställ mat Blummen'},
 'alt_training': {'en': 'Horse and rider jumping an obstacle',
                  'fr': 'Un cheval et son cavalier franchissent un obstacle',
                  'nl': 'Paard en ruiter springen over een hindernis',
                  'de': 'Pferd und Reiter beim Sprung über ein Hindernis',
                  'sv': 'Häst och ryttare hoppar över ett hinder',
                  'lb': 'Päerd a Reider iwwer engem Hindernis'},
 'alt_breeding': {'en': 'Mare and foal in a meadow',
                  'fr': 'Jument et poulain dans une prairie',
                  'nl': 'Merrie en veulen in een weide',
                  'de': 'Stute und Fohlen auf einer Wiese',
                  'sv': 'Sto och föl på en äng',
                  'lb': 'Stut a Fëll op enger Wiss'},
 'alt_facilities': {'en': 'A rider entering the outdoor arena',
                    'fr': 'Un cavalier entre dans la carrière extérieure',
                    'nl': 'Een ruiter rijdt de buitenpiste binnen',
                    'de': 'Ein Reiter betritt den Außenreitplatz',
                    'sv': 'En ryttare rider in på utomhusbanan',
                    'lb': 'E Reider kënnt an d’Baussebaan'},
 'alt_houses': {'en': 'La Grange and its outdoor pool',
                'fr': 'La Grange et sa piscine extérieure',
                'nl': 'La Grange en het buitenzwembad',
                'de': 'La Grange und ihr Außenpool',
                'sv': 'La Grange och utomhuspoolen',
                'lb': 'La Grange mat hirem Baussepool'}})

GALLERY_ALT["prepinson-ortho-25-garden-terrace.webp"] = _l("Garden and terrace at Le Cottage", "Jardin et terrasse du Cottage", "Tuin en terras van Le Cottage", "Garten und Terrasse des Cottage", "Trädgård och terrass vid Le Cottage", "Gaart an Terrass vum Cottage")
GALLERY_ALT["dalton-falsterbo-dressage.webp"] = _l("Dalton de Prepinson competing in dressage at Falsterbo", "Dalton de Prepinson en piste lors d’une épreuve de dressage à Falsterbo", "Dalton de Prepinson tijdens een dressuurproef in Falsterbo", "Dalton de Prepinson bei einer Dressurprüfung in Falsterbo", "Dalton de Prepinson under en dressyrklass i Falsterbo", "Den Dalton de Prepinson bei enger Dressurprüfung zu Falsterbo")
GALLERY_ALT["dalton-falsterbo-finish.webp"] = _l("Dalton de Prepinson and his rider at the end of their test at Falsterbo", "Dalton de Prepinson et sa cavalière à la fin de leur reprise à Falsterbo", "Dalton de Prepinson en zijn amazone aan het einde van hun proef in Falsterbo", "Dalton de Prepinson und seine Reiterin am Ende ihrer Prüfung in Falsterbo", "Dalton de Prepinson och hans ryttare efter ritten i Falsterbo", "Den Dalton de Prepinson a seng Reiderin nom Enn vun hirer Prüfung zu Falsterbo")
GALLERY_ALT["dalton-falsterbo-arena-entry.webp"] = _l("Dalton de Prepinson entering the arena at Falsterbo", "Dalton de Prepinson entre en piste à Falsterbo", "Dalton de Prepinson komt de piste in Falsterbo binnen", "Dalton de Prepinson beim Einritt in die Arena in Falsterbo", "Dalton de Prepinson på väg in på banan i Falsterbo", "Den Dalton de Prepinson kënnt zu Falsterbo an d'Pist")

UI.update({'alt_indoor': {'en': 'Interior of the indoor riding arena, with roof lights and a sand surface',
                'fr': 'Intérieur du manège couvert, avec lumière zénithale et sol en sable',
                'nl': 'Binnenzijde van de overdekte rijbaan met dakramen en zandbodem',
                'de': 'Innenansicht der Reithalle mit Oberlichtern und Sandboden',
                'sv': 'Ridhusets interiör med takfönster och sandunderlag',
                'lb': 'Bannen an der Reithal mat Daachfënsteren a Sandbuedem'},
 'alt_outdoor': {'en': 'Outdoor riding arena with show-jumping fences',
                 'fr': 'Carrière extérieure équipée d’obstacles de saut',
                 'nl': 'Buitenrijbaan met springhindernissen',
                 'de': 'Außenreitplatz mit Sprunghindernissen',
                 'sv': 'Utomhusbana med hopphinder',
                 'lb': 'Baussebaan mat Spranghindernisser'},
 'alt_paddocks': {'en': 'Horses in fenced green paddocks at Prepinson',
                  'fr': 'Chevaux dans les prairies clôturées de Prepinson',
                  'nl': 'Paarden in de omheinde groene weiden van Prepinson',
                  'de': 'Pferde auf eingezäunten grünen Weiden in Prepinson',
                  'sv': 'Hästar i inhägnade gröna hagar på Prepinson',
                  'lb': 'Päerd op agezéngte grénge Wise vu Prepinson'},
 'alt_saddle': {'en': 'Detail of a rider seated in a saddle on a horse',
                'fr': 'Détail d’un cavalier en selle sur un cheval',
                'nl': 'Detail van een ruiter in het zadel op een paard',
                'de': 'Detail eines Reiters im Sattel auf einem Pferd',
                'sv': 'Detalj av en ryttare i sadeln på en häst',
                'lb': 'Detail vun engem Reider am Suedel op engem Päerd'}})

UI["transport_access"] = {'de': 'Kontaktieren Sie das Team vor Ihrer Anreise mit einem Pferd, um die Zufahrt und den Transport abzustimmen.',
 'en': 'Before arriving with a horse, contact the team to arrange access and coordinate with your transporter.',
 'fr': 'Avant votre arrivée avec un cheval, contactez l’équipe pour organiser l’accès et vous coordonner avec votre '
       'transporteur.',
 'lb': 'Kontaktéiert d’Ekipp virun Ärer Arrivée mat engem Päerd, fir den Zougang an den Transport ofzeschwätzen.',
 'nl': 'Neem vóór aankomst met een paard contact op met het team om de toegang en het transport af te stemmen.',
 'sv': 'Kontakta teamet innan du kommer med en häst för att planera tillträde och samordna med din transportör.'}


# Final client-approved content and original photographs (V6).
from src.client_content import V1_UPDATES, UI_UPDATES, GALLERY_COPY
for _key, _values in V1_UPDATES.items():
    for _lang, _value in zip(LANGS, _values):
        V1_COPY[_lang][_key] = _value
for _key, _values in UI_UPDATES.items():
    UI[_key] = dict(zip(LANGS, _values))
for _key, _values in GALLERY_COPY.items():
    GALLERY_ALT[_key] = dict(zip(LANGS, _values))
MEDIA.update({
    "home_hero": "hero-horses-2000.webp",
    "intro": "prepinson-horse-care.webp",
    "team_eva": "eva-schiller-portrait.webp",
    "team_nicolas": "nicolas-derouault-portrait.webp",
})
