"""Presentation-only labels and media assignments for the V1 interface.

Editorial copy and metadata remain in :mod:`src.site_data`.  This module only
contains short interface labels, verified links, and the approved media map.
"""

from src.site_data import LANGS


def _l(en, fr, nl, de, sv, lb):
    return dict(zip(LANGS, (en, fr, nl, de, sv, lb)))


UI = {
    "nav_haras": _l("The haras", "Le haras", "De stoeterij", "Das Gestüt", "Stuteriet", "De Gestüt"),
    "nav_expertise": _l("Our expertise", "Notre savoir-faire", "Onze expertise", "Unser Können", "Vår expertis", "Eist Kënnen"),
    "nav_journal": _l("Journal", "Journal", "Journaal", "Journal", "Journal", "Journal"),
    "hero_cta": _l("Discover the haras", "Découvrir le haras", "Ontdek de stoeterij", "Das Gestüt entdecken", "Upptäck stuteriet", "D'Gestüt entdecken"),
    "watch_film": _l("Watch the film", "Voir le film", "Bekijk de film", "Film ansehen", "Se filmen", "Film kucken"),
    "scroll": _l("Scroll to explore", "Poursuivre la visite", "Verder ontdekken", "Weiter entdecken", "Fortsätt upptäcka", "Weider entdecken"),
    "location": _l("Ortho, Belgian Ardennes", "Ortho, Ardennes belges", "Ortho, Belgische Ardennen", "Ortho, Belgische Ardennen", "Ortho, belgiska Ardennerna", "Ortho, belsch Ardennen"),
    "intro_label": _l("The haras", "Le haras", "De stoeterij", "Das Gestüt", "Stuteriet", "De Gestüt"),
    "intro_note": _l("Trust is where it all begins.", "Tout commence par la confiance.", "Alles begint met vertrouwen.", "Alles beginnt mit Vertrauen.", "Allt börjar med tillit.", "Alles fänkt mat Vertrauen un."),
    "expertise_label": _l("Our expertise", "Notre savoir-faire", "Onze expertise", "Unser Können", "Vår expertis", "Eist Kënnen"),
    "expertise_title": _l("The care behind the potential.", "Les soins au service du potentiel.", "Zorg die potentieel laat groeien.", "Fürsorge, die Potenzial entfaltet.", "Omsorg som utvecklar potential.", "Betreiung, déi Potenzial entwéckelt."),
    "expertise_intro": _l("From the first steps to the next chapter. A considered approach at every stage.", "Des premiers pas au prochain chapitre. Une approche réfléchie à chaque étape.", "Van de eerste stappen tot het volgende hoofdstuk. Een doordachte aanpak in elke fase.", "Von den ersten Schritten bis zum nächsten Kapitel. Ein durchdachter Ansatz in jeder Phase.", "Från de första stegen till nästa kapitel. Ett genomtänkt arbetssätt i varje fas.", "Vun den éischte Schrëtt bis zum nächste Kapitel. Eng duerchduecht Approche an all Phas."),
    "breeding_title": _l("Breeding & young horses", "Élevage & jeunes chevaux", "Fokkerij & jonge paarden", "Zucht & Jungpferde", "Avel & unghästar", "Zuucht & jonk Päerd"),
    "facilities_cta": _l("Discover the facilities", "Découvrir les installations", "Ontdek de faciliteiten", "Anlage entdecken", "Upptäck anläggningen", "Infrastrukturen entdecken"),
    "references_label": _l("Born at Prepinson", "Nés à Prepinson", "Geboren bij Prepinson", "In Prepinson geboren", "Födda på Prepinson", "Zu Prepinson gebuer"),
    "team_label": _l("The people of Prepinson", "L’équipe de Prepinson", "Het team van Prepinson", "Das Team von Prepinson", "Teamet på Prepinson", "D'Ekipp vu Prepinson"),
    "team_title": _l("Experience, instinct and daily care.", "Expérience, instinct et soins quotidiens.", "Ervaring, instinct en dagelijkse zorg.", "Erfahrung, Gespür und tägliche Fürsorge.", "Erfarenhet, känsla och daglig omsorg.", "Erfarung, Instinkt an deeglech Betreiung."),
    "team_intro": _l("A small, committed team gives every horse individual attention, patience and the right environment.", "Une équipe engagée apporte à chaque cheval une attention individuelle, de la patience et un environnement adapté.", "Een betrokken team geeft elk paard individuele aandacht, geduld en de juiste omgeving.", "Ein engagiertes Team schenkt jedem Pferd individuelle Aufmerksamkeit, Geduld und das passende Umfeld.", "Ett engagerat team ger varje häst individuell uppmärksamhet, tålamod och rätt miljö.", "Eng engagéiert Ekipp gëtt all Päerd individuell Opmierksamkeet, Gedold an dat passend Ëmfeld."),
    "eva_role": _l("Manager & founder", "Gérante & fondatrice", "Manager & oprichter", "Leitung & Gründerin", "Chef & grundare", "Gerante & Grënnerin"),
    "nicolas_role": _l("Site manager", "Responsable du site", "Locatiemanager", "Betriebsleiter", "Platsansvarig", "Responsabele vum Site"),
    "houses_label": _l("Stay at Prepinson", "Séjourner à Prepinson", "Verblijven bij Prepinson", "Aufenthalt in Prepinson", "Bo på Prepinson", "Zu Prepinson bleiwen"),
    "houses_home_copy": _l("Two houses in the heart of the Ardennes, for enjoying the estate and its surroundings.", "Deux maisons au cœur des Ardennes, pour profiter du domaine et de ses environs.", "Twee huizen in het hart van de Ardennen, om van het domein en de omgeving te genieten.", "Zwei Häuser im Herzen der Ardennen, um das Anwesen und seine Umgebung zu genießen.", "Två hus i hjärtat av Ardennerna, för att njuta av gården och omgivningarna.", "Zwee Haiser am Häerz vun den Ardennen, fir d'Domaine an d'Ëmgéigend ze genéissen."),
    "houses_cta": _l("Discover the houses", "Découvrir les maisons", "Ontdek de huizen", "Häuser entdecken", "Upptäck husen", "D'Haiser entdecken"),
    "journal_label": _l("Notes from Prepinson", "Le journal de Prepinson", "Notities uit Prepinson", "Notizen aus Prepinson", "Anteckningar från Prepinson", "Notize vu Prepinson"),
    "official_link": _l("Official website", "Site officiel", "Officiële website", "Offizielle Website", "Officiell webbplats", "Offiziell Websäit"),
    "check_availability": _l("Check availability", "Consulter les disponibilités", "Beschikbaarheid bekijken", "Verfügbarkeit prüfen", "Se tillgänglighet", "Disponibilitéit kucken"),
    "other_house": _l("Discover the other house", "Découvrir l’autre maison", "Ontdek het andere huis", "Das andere Haus entdecken", "Upptäck det andra huset", "Dat anert Haus entdecken"),
    "activities_cta": _l("Explore the surroundings", "Découvrir les environs", "Ontdek de omgeving", "Umgebung entdecken", "Upptäck omgivningarna", "D'Ëmgéigend entdecken"),
    "gallery_label": _l("Photo gallery", "Galerie photos", "Fotogalerij", "Fotogalerie", "Fotogalleri", "Fotogalerie"),
    "close_gallery": _l("Close gallery", "Fermer la galerie", "Galerij sluiten", "Galerie schließen", "Stäng galleriet", "Galerie zoumaachen"),
    "previous": _l("Previous photograph", "Photo précédente", "Vorige foto", "Vorheriges Foto", "Föregående foto", "Viregt Bild"),
    "next": _l("Next photograph", "Photo suivante", "Volgende foto", "Nächstes Foto", "Nästa foto", "Nächst Bild"),
    "booking_title": _l("Plan your stay.", "Préparez votre séjour.", "Plan uw verblijf.", "Planen Sie Ihren Aufenthalt.", "Planera din vistelse.", "Plangt Ären Openthalt."),
    "capacity": _l("guests", "personnes", "gasten", "Gäste", "gäster", "Gäscht"),
    "programme_cta": _l("Talk about this programme", "Parler de ce programme", "Bespreek dit programma", "Über dieses Programm sprechen", "Prata om programmet", "Iwwer dëse Programm schwätzen"),
    "sales_cta": _l("Find a horse", "Rechercher un cheval", "Een paard zoeken", "Ein Pferd suchen", "Hitta en häst", "E Päerd sichen"),
    "read_story": _l("Read the story", "Lire son histoire", "Lees het verhaal", "Geschichte lesen", "Läs berättelsen", "Geschicht liesen"),
}


def ui(key, lang):
    """Return a required short UI label."""
    return UI[key][lang]


MEDIA = {
    "home_hero": "hero-horses-2000.webp",
    "intro": "horse-4.jpg",
    "boarding": "prepinson-stables-flowers.webp",
    "training": "training-2000.webp",
    "breeding": "prepinson-mare-and-foal.webp",
    "facilities": "facilities-2000.webp",
    "team_eva": "eva-schiller.jpg",
    "team_nicolas": "nicolas-derouault.jpg",
    "houses": "house-hero-2000.webp",
    "ortho24": "grange-1.jpg",
    "ortho25": "prepinson-ortho-25-garden-terrace.webp",
}


PROPERTIES = {
    "ortho-24": {
        "short": "Ortho 24 — La Grange",
        "image": "grange-1.jpg",
        "booking": "https://www.casapilot.com/en/1091854-holiday-home-in-la-roche-en-ardenne-ardennes-and-eifel-belgium",
        "platform": "Casapilot",
        "bedrooms": 4,
        "bathrooms": 4,
        "gallery": tuple((f"grange-{i}.jpg", f"Ortho 24 — La Grange, photograph {i}") for i in range(1, 7)),
    },
    "ortho-25": {
        "short": "Ortho 25 — Le Cottage",
        "image": "prepinson-ortho-25-garden-terrace.webp",
        "booking": "https://airbnb.com/h/ortho25",
        "platform": "Airbnb",
        "bedrooms": 3,
        "bathrooms": 3,
        "gallery": (("cottage.jpg", "Ortho 25 — Le Cottage, stone exterior"),) + tuple((f"cottage-{i}.jpg", f"Ortho 25 — Le Cottage, photograph {i}") for i in range(1, 6)),
    },
}


ACTIVITIES = (
    ("act_walk", (
        ("Ortho-Hives Tourisme", "https://www.ortho-hives-tourisme.com/randonner"),
        ("Lac et barrage de Nisramont", "https://www.la-roche-tourisme.com/le-lac-et-le-barrage-de-nisramont/"),
        ("Le Hérou", "https://www.luxembourg-belge.be/diffusio/fr/voir-faire/visiter/patrimoine-naturel/nadrin/le-herou_TFOALD-01-08H9-01.php"),
        ("Le Cheslé", "https://www.la-roche-tourisme.com/la-forteresse-celtique-du-chesle/"),
    )),
    ("act_cycle", (
        ("SoWatt e-bike", "https://sowatt.bike/fr"),
        ("Wildtrails", "https://www.wildtrails.be/"),
        ("Brandsport", "https://www.brandsport.be/"),
        ("Ardenne Aventures", "https://ardenneaventures.com/"),
        ("Trott-e-Trail", "https://www.trott-e-trail.com/"),
    )),
    ("act_family", (
        ("La Roche-en-Ardenne Tourisme", "https://www.la-roche-tourisme.com/"),
        ("Château féodal de La Roche-en-Ardenne", "https://www.chateaudelaroche.be/"),
        ("Parc à Gibier", "https://www.parc-gibier-laroche.be/"),
        ("Grottes de Hotton", "https://grottesdehotton.be/"),
        ("Parc Chlorophylle", "https://www.parcchlorophylle.com/"),
        ("Houtopia", "https://www.houtopia.be/"),
        ("Brasserie d'Achouffe", "https://chouffe.com/"),
    )),
)


# Approved V1 presentation, extracted from fd597a0; line breaks and italics are intentional.
V1_COPY = {'en': {'home_hero': 'A life dedicated<br>to <em>horses.</em>',
        'home_eyebrow': 'HARAS DE PREPINSON · BELGIUM',
        'home_tagline': 'Care without compromise.<br>Potential without limits.',
        'home_intro_title': 'Horses first.<br><em>Always.</em>',
        'home_intro': 'Great horsemanship starts with the individual. At Prepinson, we give every horse the time, attention and space to '
                      'become the best version of itself.',
        'home_intro_secondary': 'A private haras in the Belgian Ardennes, dedicated to breeding, young horse development and exceptional '
                                'daily care.',
        'home_intro_link': 'Inside our equestrian world',
        'expertise_title': 'The care behind<br><em>the potential.</em>',
        'expertise_intro': 'From the first steps to the next chapter.<br>A considered approach, at every stage.',
        'team_title': 'Experience, instinct<br><em>and daily care.</em>',
        'team_intro': 'Prepinson is shaped by a small, committed team and a shared belief: every horse deserves individual attention, '
                      'patience and the right environment.',
        'home_services_line': 'BREEDING &nbsp; / &nbsp; TRAINING &nbsp; / &nbsp; CARE',
        'hero_film': 'A moment at Prepinson<br><small>WATCH THE FILM</small>',
        'journal_title': 'The life behind<br><em>the horses.</em>',
        'journal_intro': 'A closer look at our work, through stories shared on Instagram.',
        'horses_hero': 'Great horses.<br><em>Thoughtful beginnings.</em>',
        'horses_tagline': 'Professional care. Patient training. Room to reach their potential.',
        'houses_hero': 'Make room<br><em>for slow living.</em>',
        'houses_tagline': 'Two beautiful homes. Your own corner of the Ardennes.',
        'houses_intro_title': 'Come together.<br><em>Feel at home.</em>',
        'houses_instagram_title': 'The houses,<br><em>as they are lived.</em>',
        'houses_instagram_copy': 'Seasonal details, new views and everyday moments from Ortho 24 and Ortho 25.',
        'houses_estate_title': 'Less rush.<br><em>More Ardennes.</em>',
        'houses_estate_copy': 'Walk through the forests, explore La Roche-en-Ardenne or simply find a quiet spot in the garden. The best '
                              'days here leave a little room for nothing at all.',
        'house_detail_intro': 'Your time.<br><em>Your place.</em>',
        'ortho24_copy': 'A generous Ardennes retreat, where stone walls meet contemporary comfort. Gather with family or friends, settle '
                        'into slow mornings and make the most of the pool and outdoor hot tub.',
        'ortho24_amenities': '<span>8 guests</span><span>4 bedrooms</span><span>4 bathrooms</span><span>Outdoor pool</span><span>Hot '
                             'tub</span><span>Home cinema</span>',
        'ortho25_copy': 'A welcoming stone cottage in the village of Ortho. With a private garden and space for eight, it is a lovely base '
                        'for forest walks, unhurried lunches and time together in the Ardennes.',
        'ortho25_amenities': '<span>8 guests</span><span>3 bedrooms</span><span>3 bathrooms</span><span>Private '
                             'garden</span><span>Kitchen</span><span>2 parking spaces</span>'},
 'fr': {'home_hero': 'Une vie consacrée<br>aux <em>chevaux.</em>',
        'home_eyebrow': 'HARAS DE PREPINSON · BELGIQUE',
        'home_tagline': 'Des soins sans compromis.<br>Un potentiel sans limites.',
        'home_intro_title': 'Les chevaux d’abord.<br><em>Toujours.</em>',
        'home_intro': 'Tout commence par l’attention portée à chaque cheval. À Prepinson, nous lui donnons le temps, les soins et l’espace '
                      'nécessaires pour révéler son potentiel.',
        'home_intro_secondary': 'Un haras privé dans les Ardennes belges, consacré à l’élevage, à la formation des jeunes chevaux et à des '
                                'soins quotidiens attentifs.',
        'home_intro_link': 'Entrer dans notre univers équestre',
        'expertise_title': 'Les soins au service<br><em>du potentiel.</em>',
        'expertise_intro': 'Des premiers pas au prochain chapitre.<br>Une approche réfléchie, à chaque étape.',
        'team_title': 'Expérience, instinct<br><em>et attention quotidienne.</em>',
        'team_intro': 'Prepinson est porté par une petite équipe engagée et une conviction commune : chaque cheval mérite une attention '
                      'individuelle, de la patience et un environnement adapté.',
        'home_services_line': 'ÉLEVAGE / FORMATION / SOINS',
        'hero_film': 'Un instant à Prepinson<br><small>VOIR LE FILM</small>',
        'journal_title': 'La vie derrière<br><em>les chevaux.</em>',
        'journal_intro': 'Un regard sur notre travail, à travers les histoires partagées sur Instagram.',
        'horses_hero': 'Des chevaux d’exception.<br><em>Des débuts réfléchis.</em>',
        'horses_tagline': 'Des soins professionnels. Une formation patiente. L’espace pour révéler leur potentiel.',
        'houses_hero': 'Prenez le temps<br><em>de ralentir.</em>',
        'houses_tagline': 'Deux belles maisons. Votre coin des Ardennes.',
        'houses_intro_title': 'Se retrouver.<br><em>Se sentir chez soi.</em>',
        'houses_instagram_title': 'Les maisons,<br><em>au fil des séjours.</em>',
        'houses_instagram_copy': 'Détails de saison, nouvelles perspectives et instants du quotidien à Ortho 24 et Ortho 25.',
        'houses_estate_title': 'Moins de hâte.<br><em>Plus d’Ardennes.</em>',
        'houses_estate_copy': 'Promenez-vous en forêt, découvrez La Roche-en-Ardenne ou installez-vous simplement dans le jardin. Ici, les '
                              'plus belles journées laissent une place à l’imprévu.',
        'house_detail_intro': 'Votre temps.<br><em>Votre endroit.</em>',
        'ortho24_copy': 'Un refuge spacieux dans les Ardennes, entre pierre et confort contemporain. Retrouvez-vous en famille ou entre '
                        'amis, profitez de matinées paisibles, de la piscine et du bain à remous extérieur.',
        'ortho24_amenities': '<span>8 personnes</span><span>4 chambres</span><span>4 salles de bains</span><span>Piscine '
                             'extérieure</span><span>Bain à remous</span><span>Home cinéma</span>',
        'ortho25_copy': 'Un cottage en pierre accueillant au cœur du village d’Ortho. Avec son jardin privé et sa capacité de huit '
                        'personnes, c’est le point de départ idéal pour des balades en forêt et des moments partagés dans les Ardennes.',
        'ortho25_amenities': '<span>8 personnes</span><span>3 chambres</span><span>3 salles de bains</span><span>Jardin '
                             'privé</span><span>Cuisine</span><span>2 places de parking</span>'},
 'nl': {'home_hero': 'Een leven<br>voor <em>paarden.</em>',
        'home_eyebrow': 'HARAS DE PREPINSON · BELGIË',
        'home_tagline': 'Zorg zonder compromissen.<br>Potentieel zonder grenzen.',
        'home_intro_title': 'Paarden eerst.<br><em>Altijd.</em>',
        'home_intro': 'Goed paardenmanagement begint bij het individu. Op Prepinson geven we elk paard de tijd, aandacht en ruimte die het '
                      'nodig heeft om zijn potentieel te ontwikkelen.',
        'home_intro_secondary': 'Een particuliere stoeterij in de Belgische Ardennen, gericht op fokkerij, de opleiding van jonge paarden '
                                'en aandachtige dagelijkse verzorging.',
        'home_intro_link': 'Ontdek onze paardenwereld',
        'expertise_title': 'De zorg achter<br><em>het potentieel.</em>',
        'expertise_intro': 'Van de eerste stappen tot het volgende hoofdstuk.<br>Een doordachte aanpak in elke fase.',
        'team_title': 'Ervaring, instinct<br><em>en dagelijkse zorg.</em>',
        'team_intro': 'Prepinson wordt gevormd door een klein, betrokken team en één gedeelde overtuiging: elk paard verdient persoonlijke '
                      'aandacht, geduld en de juiste omgeving.',
        'home_services_line': 'FOKKERIJ / OPLEIDING / ZORG',
        'hero_film': 'Een moment op Prepinson<br><small>BEKIJK DE FILM</small>',
        'journal_title': 'Het leven achter<br><em>de paarden.</em>',
        'journal_intro': 'Een blik op ons werk, via verhalen die we op Instagram delen.',
        'horses_hero': 'Bijzondere paarden.<br><em>Een doordachte start.</em>',
        'horses_tagline': 'Professionele zorg. Geduldige training. Ruimte om hun potentieel te ontwikkelen.',
        'houses_hero': 'Maak ruimte<br><em>voor rust.</em>',
        'houses_tagline': 'Twee mooie huizen. Uw eigen plek in de Ardennen.',
        'houses_intro_title': 'Samenkomen.<br><em>Voel u thuis.</em>',
        'houses_instagram_title': 'De huizen,<br><em>zoals ze worden beleefd.</em>',
        'houses_instagram_copy': 'Seizoensdetails, nieuwe perspectieven en alledaagse momenten uit Ortho 24 en Ortho 25.',
        'houses_estate_title': 'Minder haast.<br><em>Meer Ardennen.</em>',
        'houses_estate_copy': 'Wandel door de bossen, ontdek La Roche-en-Ardenne of zoek een rustig plekje in de tuin. De mooiste dagen '
                              'laten ruimte om even niets te doen.',
        'house_detail_intro': 'Uw tijd.<br><em>Uw plek.</em>',
        'ortho24_copy': 'Een ruim toevluchtsoord in de Ardennen, waar natuursteen en modern comfort samenkomen. Geniet met familie of '
                        'vrienden van rustige ochtenden, het zwembad en de buitenjacuzzi.',
        'ortho24_amenities': '<span>8 personen</span><span>4 slaapkamers</span><span>4 '
                             'badkamers</span><span>Buitenzwembad</span><span>Jacuzzi</span><span>Thuisbioscoop</span>',
        'ortho25_copy': 'Een gastvrije stenen cottage in het dorp Ortho. Met een privétuin en plaats voor acht personen is het een fijne '
                        'uitvalsbasis voor boswandelingen en samenzijn in de Ardennen.',
        'ortho25_amenities': '<span>8 personen</span><span>3 slaapkamers</span><span>3 '
                             'badkamers</span><span>Privétuin</span><span>Keuken</span><span>2 parkeerplaatsen</span>'},
 'de': {'home_hero': 'Ein Leben<br>für <em>Pferde sprechen.</em>',
        'home_eyebrow': 'HARAS DE PREPINSON · BELGIEN',
        'home_tagline': 'Fürsorge ohne Kompromisse.<br>Potenzial ohne Grenzen.',
        'home_intro_title': 'Pferde zuerst.<br><em>Immer.</em>',
        'home_intro': 'Gute Pferdeausbildung beginnt beim einzelnen Tier. In Prepinson geben wir jedem Pferd die Zeit, Aufmerksamkeit und '
                      'den Raum, die es braucht, um sein Potenzial zu entfalten.',
        'home_intro_secondary': 'Ein privates Gestüt in den belgischen Ardennen, das sich der Zucht, der Jungpferdeausbildung und einer '
                                'aufmerksamen täglichen Betreuung widmet.',
        'home_intro_link': 'Unsere Pferdewelt entdecken',
        'expertise_title': 'Fürsorge für<br><em>das Potenzial.</em>',
        'expertise_intro': 'Von den ersten Schritten zum nächsten Kapitel.<br>Ein durchdachter Ansatz in jeder Phase.',
        'team_title': 'Erfahrung, Gespür<br><em>und tägliche Fürsorge.</em>',
        'team_intro': 'Prepinson wird von einem kleinen, engagierten Team und einer gemeinsamen Überzeugung geprägt: Jedes Pferd verdient '
                      'individuelle Aufmerksamkeit, Geduld und das richtige Umfeld.',
        'home_services_line': 'ZUCHT / AUSBILDUNG / FÜRSORGE',
        'hero_film': 'Ein Moment in Prepinson<br><small>FILM ANSEHEN</small>',
        'journal_title': 'Das Leben hinter<br><em>den Pferden.</em>',
        'journal_intro': 'Ein Einblick in unsere Arbeit durch Geschichten auf Instagram.',
        'horses_hero': 'Besondere Pferde.<br><em>Ein durchdachter Anfang.</em>',
        'horses_tagline': 'Professionelle Betreuung. Geduldige Ausbildung. Raum, um das Potenzial zu entfalten.',
        'houses_hero': 'Zeit nehmen<br><em>für die Ruhe.</em>',
        'houses_tagline': 'Zwei schöne Häuser. Ihr Rückzugsort in den Ardennen.',
        'houses_intro_title': 'Zusammenkommen.<br><em>Sich zu Hause fühlen.</em>',
        'houses_instagram_title': 'Die Häuser,<br><em>wie sie erlebt werden.</em>',
        'houses_instagram_copy': 'Saisonale Details, neue Perspektiven und Alltagsmomente aus Ortho 24 und Ortho 25.',
        'houses_estate_title': 'Weniger Eile.<br><em>Mehr Ardennen.</em>',
        'houses_estate_copy': 'Spazieren Sie durch die Wälder, entdecken Sie La Roche-en-Ardenne oder suchen Sie sich einen ruhigen Platz '
                              'im Garten. Die schönsten Tage lassen Raum fürs Nichtstun.',
        'house_detail_intro': 'Ihre Zeit.<br><em>Ihr Ort.</em>',
        'ortho24_copy': 'Ein großzügiger Rückzugsort in den Ardennen, der Steinmauern mit modernem Komfort verbindet. Genießen Sie mit '
                        'Familie oder Freunden ruhige Morgen, den Pool und den Whirlpool im Freien.',
        'ortho24_amenities': '<span>8 Gäste</span><span>4 Schlafzimmer</span><span>4 '
                             'Badezimmer</span><span>Außenpool</span><span>Whirlpool</span><span>Heimkino</span>',
        'ortho25_copy': 'Ein einladendes Steinhaus im Dorf Ortho. Mit privatem Garten und Platz für acht Gäste ist es ein schöner '
                        'Ausgangspunkt für Waldspaziergänge und gemeinsame Zeit in den Ardennen.',
        'ortho25_amenities': '<span>8 Gäste</span><span>3 Schlafzimmer</span><span>3 Badezimmer</span><span>Privater '
                             'Garten</span><span>Küche</span><span>2 Parkplätze</span>'},
 'sv': {'home_hero': 'Ett liv<br>med <em>hästar.</em>',
        'home_eyebrow': 'HARAS DE PREPINSON · BELGIEN',
        'home_tagline': 'Omsorg utan kompromisser.<br>Potential utan gränser.',
        'home_intro_title': 'Hästarna först.<br><em>Alltid.</em>',
        'home_intro': 'God hästhållning börjar med individen. På Prepinson ger vi varje häst den tid, omsorg och det utrymme den behöver '
                      'för att utveckla sin potential.',
        'home_intro_secondary': 'Ett privat stuteri i de belgiska Ardennerna, med fokus på avel, unghästutbildning och omsorgsfull daglig '
                                'skötsel.',
        'home_intro_link': 'Upptäck vår hästvärld',
        'expertise_title': 'Omsorgen bakom<br><em>potentialen.</em>',
        'expertise_intro': 'Från de första stegen till nästa kapitel.<br>Ett genomtänkt arbetssätt i varje skede.',
        'team_title': 'Erfarenhet, känsla<br><em>och daglig omsorg.</em>',
        'team_intro': 'Prepinson formas av ett litet, engagerat team och en gemensam övertygelse: varje häst förtjänar individuell '
                      'uppmärksamhet, tålamod och rätt miljö.',
        'home_services_line': 'AVEL / UTBILDNING / OMSORG',
        'hero_film': 'Ett ögonblick på Prepinson<br><small>SE FILMEN</small>',
        'journal_title': 'Livet bakom<br><em>hästarna.</em>',
        'journal_intro': 'En närmare titt på vårt arbete genom berättelser på Instagram.',
        'horses_hero': 'Exceptionella hästar.<br><em>En genomtänkt början.</em>',
        'horses_tagline': 'Professionell omsorg. Tålmodig träning. Utrymme att utveckla sin potential.',
        'houses_hero': 'Gör plats<br><em>för lugnet.</em>',
        'houses_tagline': 'Två vackra hus. Din egen plats i Ardennerna.',
        'houses_intro_title': 'Samlas.<br><em>Känn dig hemma.</em>',
        'houses_instagram_title': 'Husen,<br><em>som de upplevs.</em>',
        'houses_instagram_copy': 'Säsongens detaljer, nya vyer och vardagsögonblick från Ortho 24 och Ortho 25.',
        'houses_estate_title': 'Mindre brådska.<br><em>Mer Ardennerna.</em>',
        'houses_estate_copy': 'Promenera i skogen, upptäck La Roche-en-Ardenne eller hitta en lugn plats i trädgården. De bästa dagarna '
                              'lämnar utrymme för att bara vara.',
        'house_detail_intro': 'Din tid.<br><em>Din plats.</em>',
        'ortho24_copy': 'En rymlig tillflyktsort i Ardennerna där stenväggar möter modern komfort. Samla familj eller vänner och njut av '
                        'lugna morgnar, poolen och bubbelpoolen utomhus.',
        'ortho24_amenities': '<span>8 gäster</span><span>4 sovrum</span><span>4 '
                             'badrum</span><span>Utomhuspool</span><span>Bubbelpool</span><span>Hemmabio</span>',
        'ortho25_copy': 'Ett välkomnande stenhus i byn Ortho. Med en privat trädgård och plats för åtta är det en fin utgångspunkt för '
                        'skogspromenader och tid tillsammans i Ardennerna.',
        'ortho25_amenities': '<span>8 gäster</span><span>3 sovrum</span><span>3 badrum</span><span>Privat '
                             'trädgård</span><span>Kök</span><span>2 parkeringsplatser</span>'},
 'lb': {'home_hero': 'E Liewen<br>fir <em>Päerd schwätzen.</em>',
        'home_eyebrow': 'HARAS DE PREPINSON · BELSCH',
        'home_tagline': 'Betreiung ouni Kompromësser.<br>Potenzial ouni Grenzen.',
        'home_intro_title': 'D’Päerd fir d’éischt.<br><em>Ëmmer.</em>',
        'home_intro': 'Gutt Päerdsbetreiung fänkt beim eenzele Päerd un. Zu Prepinson gi mir all Päerd déi Zäit, Opmierksamkeet a Plaz, '
                      'déi et brauch, fir säi Potenzial ze entwéckelen.',
        'home_intro_secondary': 'E privat Gestitt an de belschen Ardennen, dat sech der Zuucht, der Ausbildung vu jonke Päerd an enger '
                                'opmierksamer deeglecher Betreiung widmet.',
        'home_intro_link': 'Eis Päerdswelt entdecken',
        'expertise_title': 'Betreiung fir<br><em>d’Potenzial.</em>',
        'expertise_intro': 'Vun den éischte Schrëtt bis bei dat nächst Kapitel.<br>Eng duerchduechten Approche bei all Etapp.',
        'team_title': 'Erfarung, Instinkt<br><em>an deeglech Betreiung.</em>',
        'team_intro': 'Prepinson gëtt vun engem klengen, engagéierten Team an enger gemeinsamer Iwwerzeegung gepräägt: All Päerd verdéngt '
                      'individuell Opmierksamkeet, Gedold an dat richtegt Ëmfeld.',
        'home_services_line': 'ZUUCHT / AUSBILDUNG / BETREIUNG',
        'hero_film': 'E Moment zu Prepinson<br><small>DE FILM KUCKEN</small>',
        'journal_title': 'D’Liewen hannert<br><em>de Päerd.</em>',
        'journal_intro': 'En Abléck an eis Aarbecht duerch Geschichten, déi mir op Instagram deelen.',
        'horses_hero': 'Aussergewéinlech Päerd.<br><em>Duerchduechten Ufäng.</em>',
        'horses_tagline': 'Professionell Betreiung. Gedëlleg Ausbildung. Plaz, fir hiert Potenzial ze entwéckelen.',
        'houses_hero': 'Huelt Iech Zäit<br><em>fir Rou.</em>',
        'houses_tagline': 'Zwee schéin Haiser. Ären eegene Réckzuchsuert an den Ardennen.',
        'houses_intro_title': 'Zesummekommen.<br><em>Sech doheem fillen.</em>',
        'houses_instagram_title': 'D’Haiser,<br><em>wéi se gelieft ginn.</em>',
        'houses_instagram_copy': 'Saisonal Detailer, nei Perspektiven an Alldagsmomenter aus Ortho 24 an Ortho 25.',
        'houses_estate_title': 'Manner Hetz.<br><em>Méi Ardennen.</em>',
        'houses_estate_copy': 'Spadséiert duerch d’Bëscher, entdeckt La Roche-en-Ardenne oder sicht Iech eng roueg Plaz am Gaart. Déi '
                              'schéinst Deeg loossen Zäit fir einfach näischt ze maachen.',
        'house_detail_intro': 'Är Zäit.<br><em>Är Plaz.</em>',
        'ortho24_copy': 'E grousszügege Réckzuchsuert an den Ardennen, wou Steemaueren op moderne Komfort treffen. Genéisst mat der Famill '
                        'oder Frënn roueg Moien, d’Schwämm an de Whirlpool dobaussen.',
        'ortho24_amenities': '<span>8 Persounen</span><span>4 Schlofkummeren</span><span>4 Buedzëmmeren</span><span>Schwämm '
                             'dobaussen</span><span>Whirlpool</span><span>Heemkino</span>',
        'ortho25_copy': 'E gemittlecht Steehaus am Duerf Ortho. Mat engem private Gaart a Plaz fir aacht Leit ass et e flotte Startpunkt '
                        'fir Bëschspadséiergäng a gemeinsam Zäit an den Ardennen.',
        'ortho25_amenities': '<span>8 Persounen</span><span>3 Schlofkummeren</span><span>3 Buedzëmmeren</span><span>Private '
                             'Gaart</span><span>Kichen</span><span>2 Parkplazen</span>'}}

def v1(key, lang):
    return V1_COPY[lang][key]


UI.update({'ortho24_tag': {'en': 'Space to gather. Room to unwind.',
                 'fr': 'L’espace de se retrouver. Le temps de souffler.',
                 'nl': 'Ruimte om samen te komen. Tijd om te ontspannen.',
                 'de': 'Platz für Gemeinsamkeit. Raum zum Entspannen.',
                 'sv': 'Plats att samlas. Utrymme att koppla av.',
                 'lb': 'Plaz fir zesummenzekommen. Zäit fir auszespannen.'},
 'ortho25_tag': {'en': 'Country character. A cosy escape.',
                 'fr': 'Le charme de la campagne. Un cocon chaleureux.',
                 'nl': 'Landelijke charme. Een gezellig verblijf.',
                 'de': 'Ländlicher Charme. Eine gemütliche Auszeit.',
                 'sv': 'Lantlig charm. En ombonad tillflyktsort.',
                 'lb': 'Ländleche Charme. Eng gemittlech Auszäit.'},
 'pool': {'en': 'Outdoor pool',
          'fr': 'Piscine extérieure',
          'nl': 'Buitenzwembad',
          'de': 'Außenpool',
          'sv': 'Utomhuspool',
          'lb': 'Schwämm dobaussen'},
 'hot_tub': {'en': 'Hot tub',
             'fr': 'Bain à remous',
             'nl': 'Jacuzzi',
             'de': 'Whirlpool',
             'sv': 'Bubbelpool',
             'lb': 'Whirlpool'},
 'cinema': {'en': 'Home cinema',
            'fr': 'Home cinéma',
            'nl': 'Thuisbioscoop',
            'de': 'Heimkino',
            'sv': 'Hemmabio',
            'lb': 'Heemkino'},
 'garden': {'en': 'Private garden',
            'fr': 'Jardin privé',
            'nl': 'Privétuin',
            'de': 'Privater Garten',
            'sv': 'Privat trädgård',
            'lb': 'Private Gaart'},
 'kitchen': {'en': 'Kitchen', 'fr': 'Cuisine', 'nl': 'Keuken', 'de': 'Küche', 'sv': 'Kök', 'lb': 'Kichen'},
 'parking': {'en': '2 parking spaces',
             'fr': '2 places de parking',
             'nl': '2 parkeerplaatsen',
             'de': '2 Parkplätze',
             'sv': '2 parkeringsplatser',
             'lb': '2 Parkplazen'},
 'country': {'en': 'Belgium', 'fr': 'Belgique', 'nl': 'België', 'de': 'Belgien', 'sv': 'Belgien', 'lb': 'Belsch'},
 'enlarge': {'en': 'Enlarge photograph',
             'fr': 'Agrandir la photographie',
             'nl': 'Foto vergroten',
             'de': 'Foto vergrößern',
             'sv': 'Förstora fotografiet',
             'lb': 'Foto vergréisseren'}})

GALLERY_ALT = {'grange-1.jpg': {'en': 'La Grange and its outdoor pool',
                  'fr': 'La Grange et sa piscine extérieure',
                  'nl': 'La Grange en het buitenzwembad',
                  'de': 'La Grange mit Außenpool',
                  'sv': 'La Grange och utomhuspoolen',
                  'lb': 'La Grange mat Baussepool'},
 'grange-2.jpg': {'en': 'Pool terrace and stone façade',
                  'fr': 'Terrasse de la piscine et façade en pierre',
                  'nl': 'Zwembadterras en stenen gevel',
                  'de': 'Poolterrasse und Steinfassade',
                  'sv': 'Poolterrass och stenfasad',
                  'lb': 'Poolterrass a Steefassad'},
 'grange-3.jpg': {'en': 'La Grange, garden and pool seen from above',
                  'fr': 'La Grange, le jardin et la piscine vus du ciel',
                  'nl': 'La Grange, tuin en zwembad vanuit de lucht',
                  'de': 'La Grange, Garten und Pool aus der Luft',
                  'sv': 'La Grange, trädgård och pool från ovan',
                  'lb': 'La Grange, Gaart a Pool vun uewen'},
 'grange-4.jpg': {'en': 'La Grange and the neighbouring equestrian facilities',
                  'fr': 'La Grange et les installations équestres voisines',
                  'nl': 'La Grange en de aangrenzende paardenfaciliteiten',
                  'de': 'La Grange und die benachbarte Reitanlage',
                  'sv': 'La Grange och den närliggande ridanläggningen',
                  'lb': 'La Grange an déi niewendrun Infrastrukture fir Päerd'},
 'grange-5.jpg': {'en': 'Sun loungers beside the pool overlooking the fields',
                  'fr': 'Transats au bord de la piscine, face aux prairies',
                  'nl': 'Ligstoelen bij het zwembad met uitzicht op de velden',
                  'de': 'Liegestühle am Pool mit Blick auf die Wiesen',
                  'sv': 'Solstolar vid poolen med utsikt över fälten',
                  'lb': 'Loungestill beim Pool mat Vue op d’Wisen'},
 'grange-6.jpg': {'en': 'Outdoor pool and terrace facing the countryside',
                  'fr': 'Piscine extérieure et terrasse face à la campagne',
                  'nl': 'Buitenzwembad en terras met uitzicht op het platteland',
                  'de': 'Außenpool und Terrasse mit Blick aufs Land',
                  'sv': 'Utomhuspool och terrass mot landsbygden',
                  'lb': 'Baussepool an Terrass mat Vue op d’Landschaft'},
 'cottage.jpg': {'en': 'Stone exterior of Le Cottage in Ortho',
                 'fr': 'Façade en pierre du Cottage à Ortho',
                 'nl': 'Stenen buitengevel van Le Cottage in Ortho',
                 'de': 'Steinfassade des Cottage in Ortho',
                 'sv': 'Stenfasaden på Le Cottage i Ortho',
                 'lb': 'Steefassad vum Cottage zu Ortho'},
 'cottage-1.jpg': {'en': 'Le Cottage living room with red sofa',
                   'fr': 'Salon du Cottage avec canapé rouge',
                   'nl': 'Woonkamer van Le Cottage met rode bank',
                   'de': 'Wohnzimmer des Cottage mit rotem Sofa',
                   'sv': 'Vardagsrum med röd soffa i Le Cottage',
                   'lb': 'Stuff vum Cottage mat rouder Couche'},
 'cottage-2.jpg': {'en': 'Le Cottage dining room and fireplace',
                   'fr': 'Salle à manger et cheminée du Cottage',
                   'nl': 'Eetkamer en open haard van Le Cottage',
                   'de': 'Esszimmer und Kamin im Cottage',
                   'sv': 'Matrum och öppen spis i Le Cottage',
                   'lb': 'Iesszëmmer a Kamäin am Cottage'},
 'cottage-3.jpg': {'en': 'Le Cottage bedroom',
                   'fr': 'Chambre du Cottage',
                   'nl': 'Slaapkamer van Le Cottage',
                   'de': 'Schlafzimmer im Cottage',
                   'sv': 'Sovrum i Le Cottage',
                   'lb': 'Schlofzëmmer am Cottage'},
 'cottage-4.jpg': {'en': 'Le Cottage sitting and dining area',
                   'fr': 'Salon et espace repas du Cottage',
                   'nl': 'Zit- en eetruimte van Le Cottage',
                   'de': 'Wohn- und Essbereich im Cottage',
                   'sv': 'Vardagsrum och matplats i Le Cottage',
                   'lb': 'Wunn- an Iessberäich am Cottage'},
 'cottage-5.jpg': {'en': 'Entrance hall and wooden staircase in Le Cottage',
                   'fr': 'Entrée et escalier en bois du Cottage',
                   'nl': 'Entree en houten trap van Le Cottage',
                   'de': 'Eingang und Holztreppe im Cottage',
                   'sv': 'Entré och trätrappa i Le Cottage',
                   'lb': 'Agank an hëlzent Trap am Cottage'}}

UI.update({'boarding_copy': {'en': 'Individual attention, daily supervision and room to thrive. A home for every stage of life.',
                   'fr': 'Une attention individuelle, une surveillance quotidienne et de l’espace pour s’épanouir. Un lieu '
                         'adapté à chaque étape de la vie.',
                   'nl': 'Persoonlijke aandacht, dagelijks toezicht en ruimte om te groeien. Een thuis voor elke levensfase.',
                   'de': 'Individuelle Aufmerksamkeit, tägliche Betreuung und Raum zur Entfaltung. Ein Zuhause für jede '
                         'Lebensphase.',
                   'sv': 'Individuell omsorg, daglig tillsyn och utrymme att trivas. Ett hem för varje skede i livet.',
                   'lb': 'Individuell Opmierksamkeet, deeglech Kontroll a Plaz fir sech z’entwéckelen. En Doheem fir all '
                         'Liewensphas.'},
 'training_copy': {'en': 'Patient, professional young horse training. Strong foundations for a future in sport.',
                   'fr': 'Une formation patiente et professionnelle des jeunes chevaux. Des bases solides pour leur avenir '
                         'sportif.',
                   'nl': 'Geduldige, professionele opleiding van jonge paarden. Een stevige basis voor een toekomst in de sport.',
                   'de': 'Geduldige, professionelle Jungpferdeausbildung. Ein solides Fundament für die sportliche Zukunft.',
                   'sv': 'Tålmodig och professionell unghästutbildning. En stabil grund för framtiden inom sporten.',
                   'lb': 'Gedëlleg a professionell Ausbildung vu jonke Päerd. Eng zolidd Basis fir hir sportlech Zukunft.'},
 'breeding_copy': {'en': 'Thoughtful beginnings. Bringing together promising bloodlines and attentive horsemanship.',
                   'fr': 'Des débuts réfléchis. Des lignées prometteuses accompagnées d’un travail attentif au quotidien.',
                   'nl': 'Een doordachte start. Veelbelovende bloedlijnen en aandachtige dagelijkse begeleiding.',
                   'de': 'Durchdachte Anfänge. Vielversprechende Blutlinien und aufmerksame tägliche Arbeit.',
                   'sv': 'En genomtänkt start. Lovande blodslinjer och omsorgsfullt dagligt arbete.',
                   'lb': 'Duerchduechten Ufäng. Villverspriechend Bluttlinnen an opmierksam deeglech Aarbecht.'},
 'boarding_title': {'en': 'Boarding & care',
                    'fr': 'Pension & soins',
                    'nl': 'Pension & verzorging',
                    'de': 'Pension & Betreuung',
                    'sv': 'Inackordering & omsorg',
                    'lb': 'Pensioun & Betreiung'},
 'training_title': {'en': 'Training & development',
                    'fr': 'Formation & valorisation',
                    'nl': 'Training & ontwikkeling',
                    'de': 'Ausbildung & Entwicklung',
                    'sv': 'Utbildning & utveckling',
                    'lb': 'Ausbildung & Entwécklung'},
 'horses_intro_first': {'en': 'Every horse.',
                        'fr': 'Chaque cheval.',
                        'nl': 'Elk paard.',
                        'de': 'Jedes Pferd.',
                        'sv': 'Varje häst.',
                        'lb': 'All Päerd.'},
 'horses_intro_second': {'en': 'Every possibility.',
                         'fr': 'Toutes les possibilités.',
                         'nl': 'Alle mogelijkheden.',
                         'de': 'Alle Möglichkeiten.',
                         'sv': 'Alla möjligheter.',
                         'lb': 'All Méiglechkeeten.'},
 'alt_hero': {'en': 'Mares and foals grazing in the Prepinson pastures',
              'fr': 'Juments et poulains dans les prairies de Prepinson',
              'nl': 'Merries en veulens in de weiden van Prepinson',
              'de': 'Stuten und Fohlen auf den Weiden von Prepinson',
              'sv': 'Ston och föl på Prepinsons betesmarker',
              'lb': 'Stuten a Fëlle bei Prepinson op der Wiss'},
 'alt_intro': {'en': 'A horse and its handler at Prepinson',
               'fr': 'Un cheval et la personne qui en prend soin à Prepinson',
               'nl': 'Een paard en zijn verzorger bij Prepinson',
               'de': 'Ein Pferd und seine Betreuungsperson in Prepinson',
               'sv': 'En häst och dess skötare på Prepinson',
               'lb': 'E Päerd a seng Betreiungspersoun zu Prepinson'},
 'alt_boarding': {'en': 'Horses at the windows of flower-lined stables',
                  'fr': 'Chevaux aux fenêtres des écuries fleuries',
                  'nl': 'Paarden aan de ramen van de stallen met bloemen',
                  'de': 'Pferde an den Fenstern der blumengeschmückten Ställe',
                  'sv': 'Hästar vid fönstren i de blomsterprydda stallen',
                  'lb': 'Päerd un de Fënstere vun de Ställ mat Blummen'},
 'alt_training': {'en': 'Horse and rider jumping an obstacle',
                  'fr': 'Un cheval et son cavalier franchissent un obstacle',
                  'nl': 'Paard en ruiter springen over een hindernis',
                  'de': 'Pferd und Reiter beim Sprung über ein Hindernis',
                  'sv': 'Häst och ryttare hoppar över ett hinder',
                  'lb': 'Päerd a Reider iwwer engem Hindernis'},
 'alt_breeding': {'en': 'Mare and foal in a meadow',
                  'fr': 'Jument et poulain dans une prairie',
                  'nl': 'Merrie en veulen in een weide',
                  'de': 'Stute und Fohlen auf einer Wiese',
                  'sv': 'Sto och föl på en äng',
                  'lb': 'Stut a Fëll op enger Wiss'},
 'alt_facilities': {'en': 'A rider entering the outdoor arena',
                    'fr': 'Un cavalier entre dans la carrière extérieure',
                    'nl': 'Een ruiter rijdt de buitenpiste binnen',
                    'de': 'Ein Reiter betritt den Außenreitplatz',
                    'sv': 'En ryttare rider in på utomhusbanan',
                    'lb': 'E Reider kënnt an d’Baussebaan'},
 'alt_houses': {'en': 'La Grange and its outdoor pool',
                'fr': 'La Grange et sa piscine extérieure',
                'nl': 'La Grange en het buitenzwembad',
                'de': 'La Grange und ihr Außenpool',
                'sv': 'La Grange och utomhuspoolen',
                'lb': 'La Grange mat hirem Baussepool'}})

GALLERY_ALT["prepinson-ortho-25-garden-terrace.webp"] = _l("Garden and terrace at Le Cottage", "Jardin et terrasse du Cottage", "Tuin en terras van Le Cottage", "Garten und Terrasse des Cottage", "Trädgård och terrass vid Le Cottage", "Gaart an Terrass vum Cottage")

UI.update({'alt_indoor': {'en': 'Interior of the indoor riding arena, with roof lights and a sand surface',
                'fr': 'Intérieur du manège couvert, avec lumière zénithale et sol en sable',
                'nl': 'Binnenzijde van de overdekte rijbaan met dakramen en zandbodem',
                'de': 'Innenansicht der Reithalle mit Oberlichtern und Sandboden',
                'sv': 'Ridhusets interiör med takfönster och sandunderlag',
                'lb': 'Bannen an der Reithal mat Daachfënsteren a Sandbuedem'},
 'alt_outdoor': {'en': 'Outdoor riding arena with show-jumping fences',
                 'fr': 'Carrière extérieure équipée d’obstacles de saut',
                 'nl': 'Buitenrijbaan met springhindernissen',
                 'de': 'Außenreitplatz mit Sprunghindernissen',
                 'sv': 'Utomhusbana med hopphinder',
                 'lb': 'Baussebaan mat Spranghindernisser'},
 'alt_paddocks': {'en': 'Horses in fenced green paddocks at Prepinson',
                  'fr': 'Chevaux dans les prairies clôturées de Prepinson',
                  'nl': 'Paarden in de omheinde groene weiden van Prepinson',
                  'de': 'Pferde auf eingezäunten grünen Weiden in Prepinson',
                  'sv': 'Hästar i inhägnade gröna hagar på Prepinson',
                  'lb': 'Päerd op agezéngte grénge Wise vu Prepinson'},
 'alt_saddle': {'en': 'Detail of a rider seated in a saddle on a horse',
                'fr': 'Détail d’un cavalier en selle sur un cheval',
                'nl': 'Detail van een ruiter in het zadel op een paard',
                'de': 'Detail eines Reiters im Sattel auf einem Pferd',
                'sv': 'Detalj av en ryttare i sadeln på en häst',
                'lb': 'Detail vun engem Reider am Suedel op engem Päerd'}})

UI["transport_access"] = {'de': 'Kontaktieren Sie das Team vor Ihrer Anreise mit einem Pferd, um die Zufahrt und den Transport abzustimmen.',
 'en': 'Before arriving with a horse, contact the team to arrange access and coordinate with your transporter.',
 'fr': 'Avant votre arrivée avec un cheval, contactez l’équipe pour organiser l’accès et vous coordonner avec votre '
       'transporteur.',
 'lb': 'Kontaktéiert d’Ekipp virun Ärer Arrivée mat engem Päerd, fir den Zougang an den Transport ofzeschwätzen.',
 'nl': 'Neem vóór aankomst met een paard contact op met het team om de toegang en het transport af te stemmen.',
 'sv': 'Kontakta teamet innan du kommer med en häst för att planera tillträde och samordna med din transportör.'}
